documentstore_migracao/utils/convert_html_body.py, tests/test_convert_html_body.py, tests/test_export.py
Melhoria no código do testes e correção no LiPipe()
=> task_create_testes_para_HTML2SPSPipeline

documentstore_migracao/utils/convert_html_body.py, tests/test_convert_html_body.py
e cuidando do que é válido dentro de list-item
=> tk9 Tratamento de li, convertendo para list-item

documentstore_migracao/processing/inserting.py
Esse PR completa a implementação do mecanismo de importação dos pacotes sps (xml e ativos digitais) no document-store, conforme descrito no ticket #27 
Pelo arquivo
* `documentstore_migracao/processing/inserting.py`
Utilizando o mesmo para importar os ativos digitais no Object-store
```bash
import_documents import  --minio_host play.min.io:9000 --minio_access_key minio --minio_secret_key minio123 --uri=mongodb://localhost:27017 --db=document-store
```
N/A
#27 
#47 
#19 
#54 
#55
=> Importando  os Pacotes SPS dos artigos no `document-store`

documentstore_migracao/config.py, documentstore_migracao/export/sps_package.py, documentstore_migracao/processing/inserting.py, documentstore_migracao/utils/constructor_xml.py, documentstore_migracao/utils/files.py, documentstore_migracao/utils/scielo_ids_generator.py, documentstore_migracao/utils/string.py, documentstore_migracao/utils/xylose_converter.py, tests/test_inserting.py, tests/test_sps_package.py, tests/test_utils.py, tests/test_utils_scielo_ids_generator.py
Faz o relacionamento entre os documentos registrados e os seus fascículos registrados, após ter sido feita a inserção dos documentos no Object Store e no Document Store.
- `documentstore_migracao/processing/inserting.py`
- `python setup.py test -s tests/test_inserting.py`
- `python setup.py test -s tests/test_processing_inserting.py`
AOP não estão sendo tratados ainda.
N/A
#48 
Indique as referências utilizadas para a elaboração do pull request.
=> Faz o relacionamento entre os documentos registrados e os seus fascículos registrados

documentstore_migracao/utils/convert_html_body.py, tests/test_convert_html_body.py
Corrige a conversão do elemento a que inseria incorretamente um parágrafo gerando erro na validação do XML e faz melhorias no código
- `documentstore_migracao/utils/convert_html_body.py`:422(APipe.transform)
- `tests/test_convert_html_body.py`:356-492
- `python setup.py test -s tests/test_convert_html_body.py`
N/A
N/A
#44
N/A
=> Corrige a conversão do elemento a

documentstore_migracao/utils/convert_html_body.py, tests/test_convert_html_body.py
Remove os elementos p que são pais de elementos p pois não são estruturas válidas
tests/test_convert_html_body.py:634
``python setup.py test -s tests/test_convert_html_body.py``
N/A
N/A
#44
https://jats.nlm.nih.gov/publishing/tag-library/1.2/element/p.html
=> Remove os elementos p que são pais de elementos p

tests/test_migrate_articlemeta.py
Esse PR corrige os teste do utilitario de migração devido a alteração dos nomes do comando no utilitario de migração
Pelo arquivo `tests/test_migrate_articlemeta.py`
Apos atualizar o código, rodar os teste manualmente 
#82
=>  Fix no test do test_migrate_articlemeta #82

documentstore_migracao/processing/conversion.py, documentstore_migracao/processing/packing.py, documentstore_migracao/processing/validation.py, documentstore_migracao/tools/constructor.py, documentstore_migracao/tools/generation.py, documentstore_migracao/utils/logger.py
Fale sobre o propósito do pull request como por exemplo: quais problemas ele soluciona ou quais features ele adiciona.
Pelo arquivos dos modulos:
* `documentstore_migracao.processing`
*  `documentstore_migracao.tools`
Apos atualizar o código vc pode rodar o fluxo de migração novamente, como descrito no link abaixo:
[Fuxo da migração](https://github.com/scieloorg/document-store-migracao/wiki/Fuxo-de-processamento-da-migra%C3%A7%C3%A3o)
#67 
https://github.com/tqdm/tqdm
=> Adição do tqdm para a Barra de progresso do fluxo de migraçao

documentstore_migracao/utils/convert_html_body.py, tests/test_convert_html_body.py
porque xmltree.remove conteúdo a mais
Substitui o uso de `xmltree.remove()` por `_remove_element_or_comment`
`tests/test_convert_html_body.py`
- `python setup.py test -s tests/test_convert_html_body.py`
N/A
N/A
#74 
https://lxml.de/tutorial.html (tail)
=> Substitui o uso de xmltree.remove() por _remove_element_or_comment

documentstore_migracao/utils/convert_html_body.py, tests/test_convert_html_body.py
Adiciona atributos temp_id e temp_reftype em img/@src e a/@href a partir do path do arquivo do asset. Isso ajudará a identifcar o @id de table-wrap e fig, e também @rid dos respectivos xref.
- tests/test_convert_html_body.py
`python setup.py test -s tests.test_convert_html_body.TestTempIdToAsset
`
N/A
N/A
#109, #44
N/A
=> Identifica temp_id e temp_reftype em img/@src e a/@href 

documentstore_migracao/utils/convert_html_body.py, tests/test_convert_html_body.py
Correções em ANamePipe e nos testes
documentstore_migracao/utils/convert_html_body.py
`python setup.py test -s tests.test_convert_html_body`
N/A
N/A
#109 
N/A
=> Correções em ANamePipe e nos testes

documentstore_migracao/processing/validation.py, tests/samples/0034-8910-rsp-48-2-0347-valid.xml
Esse PR Corrige o problema de validação dos XMLs descrito no ticket #104 
Pelo arquivo
* `documentstore_migracao/processing/validation.py`
```bash
$ python setup.py test -s tests.test_processing.TestProcessingValidation
```
fixe #104
=> Correção do metodo de validação todos XML

documentstore_migracao/config.py, documentstore_migracao/processing/validation.py, documentstore_migracao/utils/convert_html_body.py, tests/test_convert_html_body.py
Corrige a identificação de ativos digitais pelos nome dos arquivos, identifica novo tipo "apêndice".
Desafio de associar elementos pelo ID e pelo nome do arquivo quando não são similares. Por exemplo, name="app01" e arquivo="a05tab03".
Também permite escolher o modo de validar: VALIDATE_ALL=FALSE
Ver os testes
python setup.py test -s tests.test_convert_html_body
**Relatório ANTES**
```
Element a is not declared in p list of possible children - 4
Element back is not declared in bold list of possible children - 1
Element body content does not follow the DTD, expecting ((address | alternatives - 459
Element cite is not declared in ext-link list of possible children - 1
Element cite is not declared in p list of possible children - 3
Element country-region is not declared in p list of possible …
```
=> Corrige a identificação de ativos digitais pelos nomea dos arquivos, identifica novo tipo "apêndice"

documentstore_migracao/processing/packing.py
Esse PR incorpora uma melhoria no processamento de download da imagens dos pacotes SPS.
Essa melhoria se deve, pois a cada vez que executava o comando de `pack` do utilitario de migração, seria baixado todas as imagens novamente, e com essa melhoria o mecanismo não realizar download de images que ja tenha baixado anteriormente.
Com isso o re-processamento, ficou mais rapido, pois não a o download de todas as imagens novamente, so a leitura do disco para checar se a imagem ja foi baixa ou não
Pelo arquivos:
* `documentstore_migracao/processing/packing.py`
* Para realizar o teste manualmente , execute o download arquivos pelo comando 
```
$ ds_migracao pack
```
* Interrompa a execução pelo `ctrl+c`
* Execute novamente o comando de `download` e verifique no log a saida das linhas:
``` …
```
=> Adição de mecanismo para não realizar download de images

documentstore_migracao/utils/convert_html_body.py
Resolve o problema de codificação do conteúdo do HTML importado e inserido no body,
que apresentava: `Â `
```html
<table-wrap id="a05tab01">
<table-wrap id="tab01"><graphic xlink:href="/img/revistas/eq/v33n3/a05tab01.gif"/></table-wrap><p/>
<p>Â </p>
<p>Â </p>
<p><table-wrap id="tab02"><graphic xlink:href="/img/revistas/eq/v33n3/a05tab02.gif"/></table-wrap><table-wrap id="a05tab02"/></p>
<p>Â </p>
<p>Â </p>
<p><table-wrap id="tab03"><graphic xlink:href="/img/revistas/eq/v33n3/a05tab03.gif"/></table-wrap><table-wrap id="a05tab03"/></p>
<p>Â </p>
<p>Â </p>
<p/>
<p>Â </p>
<p>Â </p>
<p/>
```
com a correção, resulta:
```html
<p><table-wrap id="a05tab01">
<table-wrap id="tab01"><graphic xlink:href="/img/revistas/eq/v33n3/a05tab01.gif"/></table-wrap><p/>
<p><table-wrap id="tab02"><graphic …
```
=> [dsm][conversao][154-01b] Corrige a codificação do conteúdo do HTML importado e inserido no body

documentstore_migracao/utils/convert_html_body.py
Corrige dois bugs causados por #187 e #189, relacionados com a ausência de conversão de `a[@href]`.
1. Gera ext-link para `a[@href]` quando o padrao é um site mas sem http ou https
2. corrige o problema de não identificar localização de ativos digitais por estarem fora do padrão /img/revistas/
1. documentstore_migracao/utils/convert_html_body.py: L 881
2. documentstore_migracao/utils/convert_html_body.py: L 2492
1. `ds_migracao convert --file xml/source/S0044-59672013000100005.xml`
2. `ds_migracao convert --file xml/source/S1516-14392002000300005.xml`
Alguns casos não solucionados, que não geraram tags SPS correspondente porque não existe o `a[@name]` correspondente ao `a[@href]`. Será necessário avaliar cada caso se é ausência de dado ou erro de conversão, que devem ser resolvidos em …
=> [dsm][conversao] Resolve alguns erros de "Element a is not declared ..."

documentstore_migracao/utils/convert_html_body.py, tests/test_convert_html_body.py
Os elementos table do HTML, pode tanto representar um ativo digital table-wrap, mas também ser usado como elemento de diagramação, neste caso o elemento ao qual deve ser convertido é array.
documentstore_migracao/utils/convert_html_body.py L:2043
`python setup.py test -s tests.test_convert_html_body.TestTablePipe`
`ds_migracao convert --file xml/source/<arquivo>.xml`
Alguns PIDs:
- S0011-52581997000300005
- S0011-52582000000300005
- S0011-52582004000300005
- S0021-75572002000300005
- S0101-20612007000300005
- S0101-20612008000300005
- S0101-546X2002000300005
- S0101-74382005000300005
- S0101-74382011000300005
- S0101-81752003000300005
- S1981-77462011000300005
n/a
n/a
n/a
https://jats.nlm.nih.gov/publishing/tag-library/1.2d2/element/array.html
=> [dsm][conversao] Converte table para array, se não é ativo digital

documentstore_migracao/utils/xylose_converter.py
Acrescenta dados de cidade, estado, país e código de país para Journal
`documentstore_migracao/utils/xylose_converter.py`
n/a
n/a
n/a
Resolve parte de https://github.com/scieloorg/opac/issues/1454
n/a
=> Acrescenta dados de cidade, estado, país e código de país para Journal

documentstore_migracao/utils/convert_html_body.py, tests/test_convert_html_body.py
Resolve problema de travamento ao executar "convert" do arquivo S0100-879X2010001000001
veja por commits
`ds_migracao convert --file xml/source/S0100-879X2010001000001.xml`
O problema de travamento foi resolvido, no entanto, o XML gerado não está correto. O problema deve ser resolvido em outro ticket  #238
Quando aplicável e se fizer possível adicione screenshots que remetem a situação gráfica do problema que o pull request resolve.
#236 
n/a
=> Resolve problema de travamento ao executar "convert" do arquivo S0100-879X2010001000001

documentstore_migracao/utils/convert_html_body.py, requirements.txt, tests/test_convert_html_body.py
Corrige a conversão que estava removendo "imagens" a mais e também causava indiretamente mais adiante um problema de segment fault.
por commits
`ds_migracao --loglevel DEBUG convert`
Tendo arquivos em `xml/source`
n/a
n/a
#287 
n/a
=> Corrige a conversão que estava removendo "imagens" a mais

documentstore_migracao/export/sps_package.py, documentstore_migracao/object_store/minio.py, documentstore_migracao/processing/conversion.py, documentstore_migracao/processing/inserting.py, documentstore_migracao/processing/packing.py, documentstore_migracao/processing/validation.py, documentstore_migracao/utils/convert_html_body.py, documentstore_migracao/utils/xml.py, tests/test_utils.py
Altera em vários arquivos o nível de log para `debug` e assim torna possível acompanharmos os erros e mensagens importantes no arquivo `migracao.log`.
N/A
- Rodar a conversão de alguns XMLs;
- Rodar o comando `tail migracao.log`;
- Observar que o arquivo não está poluído de informações pouco relevantes para o ambiente de produção.
N/A
N/A
N/A
N/A
=> Altera o nível de log durante o processado de migração de XMLs

documentstore_migracao/utils/convert_html_body.py
Remove `<img src=""/>`
Por commits
`ds_migracao --loglevel DEBUG convert --file xml/source/S1413-82712005000200002.xml`
`ds_migracao --loglevel DEBUG convert --file xml/source/S1677-55382010000400010.xml`
`ds_migracao --loglevel DEBUG convert --file xml/source/S1677-55382010000400012.xml`
leia comentários no issue #295
n/a
#295
n/a
=> Corrige o erro que interrompe a conversão ao corrigir os caminhos dos ativos digitais

documentstore_migracao/utils/convert_html_body.py, tests/test_convert_html_body.py
Corrige a conversão de notas de rodapé (FnFixContentPipe): list index out of range
Por commits
`python setup.py test -s tests.test_convert_html_body.TestFnFixLabel`
ou 
`ds_migracao --loglevel DEBUG convert --file xml/source/S0036-46652001000400002.xml`
Outros exemplos:
- /home/scielo/spf/document-store-migracao/xml/source/S0103-97332000000100016.xml;list index out of range
- /home/scielo/spf/document-store-migracao/xml/source/S0036-46652001000200004.xml;list index out of range
- /home/scielo/spf/document-store-migracao/xml/source/S0036-46652001000400010.xml;list index out of range
- /home/scielo/spf/document-store-migracao/xml/source/S0036-46651998000600004.xml;list index out of range
- /home/scielo/spf/document-store-migracao/xml/source/S0100-204X2001000700007.xml;list index out of …
=> Corrige a conversão de notas de rodapé (FnFixContentPipe): list index out of range

requirements.txt, setup.py
Este PR atualiza a versão do Packtools, que permite que documentos em XML nativo, mesmo não sendo válidos, sejam lidos e otimizados para WEB.
No `setup.py`
Com o CSV contendo documentos em XML nativo inválidos ([1]), com problemas na otimização WEB:
2. Durante o empacotamento o erro com a mensagem `Error creating XMLWebOptimiser for` não deve ocorrer.
Este PR não resolve os erros dos ativos digitais ou PDFs que eventualmente ocorrerão no empacotamento dos documentos presentes no CSV.
n/a
[[1] - nativos-InvalidXMLs.txt](https://github.com/scieloorg/document-store-migracao/files/4583065/nativos-InvalidXMLs.txt)
#317
.
=> Atualiza versão do Packtools p/ corrigir leitura de XMLs na otimização

documentstore_migracao/utils/build_ps_package.py
Este pull request altera a fonte de cópia dos assets de acordo com o tipo de arquivo a ser copiado. Foi escolhido não separar a obtenção dos arquivo suplementares em outro método porque a super classe `SPS_Package` implementa a lógica e isso poderia ocasionar problemas em vários outros pontos.
- `documentstore_migracao/utils/build_ps_package.py` L: `283`
- Fazer o download a lista de documentos que apresentaram problemas durante o processamento, em [1];
- Realizar o empacotamento;
- Verificar que os arquivos suplementares **que existem** no ponto de montagem foram copiados.
Percebi que alguns artigos apontam para outros XMLs como arquivos suplementares e que não estão disponíveis no site clássico.
N/A
[[1] - …
=> Possibilita a cópia de materiais suplementares durante empacotamento

documentstore_migracao/processing/inserting.py, documentstore_migracao/processing/rollback.py, documentstore_migracao/utils/scielo_ids_generator.py, documentstore_migracao/utils/xylose_converter.py, setup.py, tests/test_utils_scielo_ids_generator.py, tests/test_xylose_converter.py
Corrige a função `issue_id` para que considere os valores `00` para `number` e `volume` equivalente a `None`
Por commits
verificar a seção "como reproduzir o problema" do issue #358 
n/a
n/a
#358
n/a
=> Corrige a função `issue_id` para que considere os valores `00` para `number` e `volume` equivalente a `None`

scripts/html_pid_spliter.sh
Adiciona um script shell para dividir a lista de pids dos documentos HTML. O script requer 3 argumentos: arquivo de entrada, ano de inicio e ano de fim.
=> Adiciona script para dividir a lista de PIDs de documentos html

docs/001-html-migration.md, scripts/migracao_html.sh
Este PR complementa o script que auxilia a migração para que ao término dos passos iniciais algumas contabilizações sejam feitas. Esta é uma forma de padronizar as métricas que são disponibilizadas em nossos documentos de relatório.
Recomendo a revisão por commits.
- Execute o script com alguns pids de documentos HTML.
- Verifique que ao término da execução, um novo arquivo é gerado na pasta `reports`;
Este script não elimina as verificações manuais de busca por erros.
N/A
N/A
N/A
=> Adiciona algumas métricas sobre erros ocorridos durante as fases de conversão, atualização de citações e empacotamento

documentstore_migracao/export/sps_package.py, documentstore_migracao/processing/packing.py, documentstore_migracao/utils/convert_html_body.py, tests/samples/S0044-59672003000300002_sps_completo.xml, tests/test_convert_html_body.py, tests/test_migrate_articlemeta.py, tests/test_processing_packing.py
Melhora o registro de erros, de forma que deve ser registrado como ERROR somente aquilo que impossibilita a conversão e/ou o empacotamento com sucesso, além disso incluir o pid v2 nestas mensagens.
por commits
Executar o pack e o convert e observar o log
n/a
n/a
#384
n/a
=> [html][pack e convert] Melhora o registro de erros

documentstore_migracao/object_store/minio.py, documentstore_migracao/processing/inserting.py, documentstore_migracao/utils/logger.py, scripts/loggeranalyzer.py, tests/test_inserting.py
Inclui algumas alterações feitas diretamente no dsteste
Por commits
-
- As alterações não foram feitas por mim, então não sei dizer o motivo de cada uma delas
- uma das alterações não fiz devido à dúvida se deveria ser efetuada ou não. Veja meu comentário em #390
- uma das alterações feitas no dsteste inseriu bug: não grava o erro no arquivo. O commit https://github.com/scieloorg/document-store-migracao/pull/404/commits/8814901fca4565238ed6f07d086db73394b924a1 corrige o problema. 
n/a
#390
n/a
=> Inclui algumas alterações feitas diretamente no dsteste

documentstore_migracao/processing/rollback.py
Este PR corrige o rollback para que, caso não encontre registros relacionados ao documento a serem deletados, não interrompa a execução do comando. É necessário garantir que todos os registros de todas as collections (`documents`, `documents_bundles` e `changes`) não existam. Se eles não existem, loga a mensagem e continua a execução.
Commit af81afb.
- Importe um documento para o Kernel
- Execute o comando `ds_migracao rollback` com o arquivo de saída do import
- Verifique as collections `documents`, `documents_bundles` e `changes` no MongoDB do Kernel. Nenhum registro do documento deve existir.
- Verifique o arquivo de saída do comando rollback, informado no argumento `--output`. O documento importado no passo 1 deve constar no arquivo.
.
.
#416
.
=> Trata exceções no rollback de registros não encontrados
