scieloorg/document-store-migracao

documentstore_migracao/config.py, documentstore_migracao/main.py, documentstore_migracao/processing/conversion.py, documentstore_migracao/processing/generation.py, documentstore_migracao/processing/reading.py, documentstore_migracao/processing/validation.py, documentstore_migracao/utils/dicts.py, documentstore_migracao/utils/files.py, documentstore_migracao/webserver/views.py, tests/test_main.py, tests/test_processing.py, tests/test_utils.py, tests/test_webserver.py
Reorganiza os arquivos XML em pastas de acordo com a sua situação nas etapas de migração. 
Após validar o XML, dependendo do resultado, há movimentações de arquivos para pastas correspondentes.
**1. Novos items no config**
- **PROCESSED_SOURCE_PATH**: arquivos movidos de `SOURCE_PATH`, se após convertidos para SPS estão sem erro.
- **VALID_XML_PATH**: arquivos "XML SPS" sem erros.
- **XML_ERRORS_PATH**: arquivos .err cujo conteúdo é XML + mensagens de erro.
- **SPS_PKG_PATH**: pacotes sps validados e nomeados de acordo com as recomendações.
**2. CONVERSION_PATH e VALID_XML_PATH**
Onde a pasta `CONVERSION_PATH` era entrada, a pasta `VALID_XML_PATH` também foi incluída como entrada, pois os XML válidos que estavam em `CONVERSION_PATH` foram movidos para a pasta `VALID_XML_PATH`.
**3. …
=> Reorganiza os arquivos XML em pastas correspondentes a sua situação nas etapas de migração

documentstore_migracao/__init__.py, documentstore_migracao/config.py, documentstore_migracao/exceptions.py, requirements.txt
Adiciona o `documentstore` como dependência, utiliza do seu MongoDB adapter para estabelecer a camada de conexão com o banco de dados.
- `documentstore_migracao/__init__.py` linha `18`
- `documentstore_migracao/config.py` linha `15`
Deve-se:
- Executar o interpretador python;
- Importar a session `from documentstore_migracao import session`
- Realizar alguma busca e.g `session.journals.fetch("1806-907X")`
N/A
N/A
N/A
=> Adiciona adapter e modo para inicializar a conexão com o MongoDB

README.md, documentstore_migracao/export/journal.py, documentstore_migracao/main.py, documentstore_migracao/processing/pipeline.py, documentstore_migracao/processing/reading.py, documentstore_migracao/utils/extract_isis.py, setup.py, tests/test_export.py, tests/test_migrate_isis.py, tests/test_processing.py
Este pull request refatora o comando de migração da base ISIS com o intuito de possibilitar ao usuário uma maior flexibilidade e controle sobre as opções disponíveis pela ferramenta de linha de comando.
- `documentstore_migracao/main.py` linha `122`
Deve-se:
- Executar o comando `migrate_isis -h` e experimentar as opções apresentadas pela ferramenta.
N/A
https://github.com/scieloorg/document-store/issues/143
N/A
=> Refatora comando de migração para bases ISIS

documentstore_migracao/export/sps_package.py, tests/test_sps_package.py
Cria uma classe que contém as regras para nomear os pacotes SPS a partir dos dados encontrados no XML.
- tests/test_sps_package.py
- documentstore_migracao/export/sps_package.py
``python setup.py test -s tests/test_sps_package.py``
Devido a existência de documentos do legado HTML cujos dados podem ser insuficientes para gerar nomes únicos, as regras de nomeação foram adaptadas.
Nem todos aop possuem DOI, nem elocation, nem volume, número, por isso:
De ``` ISSN-acrônimo-nahead-nº lote```
Para ``` ISSN-acrônimo-nahead-YEAR-ORDER```
Documentos sem fpage, lpage, DOI, elocation, ...
De ``` ISSN-acrônimo-volume-numero```
Para ``` ISSN-acrônimo-volume-numero-YEAR-ORDER```
Todos os demais documentos que tenha fpage e lpage, mas que potencialmente podem ter mesmo valor de fpage e lpage.
De ``` …
```
=> Criar um "nomeador de pacotes" SPS

documentstore_migracao/export/sps_package.py, tests/test_sps_package.py
Acrescenta funcionalidade de retornar nome para os ativos digitais
documentstore_migracao/export/sps_package.py
documentstore_migracao/tests/test_sps_package.py
```python setup.py test -s tests/test_sps_package.py```
Adotado o ```-g``` para gerar o nome da imagem. Por exemplo:
- nome do arquivo do documento: a01.html
- nome do ativo do documento: a01f01.jpg
- novo nome: ```<novo nome>```-gf01.jpg
- nome do ativo do documento: img.jpg
- novo nome: ```<novo nome>```-gimg.jpg
N/A
#26 
baseado em: 
https://www.ncbi.nlm.nih.gov/pmc/pub/filespec-delivery/
https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/latest/narr/regra-nomeacao.html#nomeacao-de-arquivos
=> [document-store-migracao] Nomeador dos ativos digitais

README.md, documentstore_migracao/__init__.py, documentstore_migracao/main.py, documentstore_migracao/processing/pipeline.py, tests/apptesting.py, tests/test_migrate_isis.py
Este pull request adiciona o código necessário para que os periódicos extraídos de um arquivo MST sejam inseridos em uma base MongoDB.
- `documentstore_migracao/main.py` linhas `127`, `155` e `176`
Para testar manualmente deve-se:
- Realizar a extração de uma base MST para o formato JSON
- Executar o comando `migrate_isis import -h`
- Configurar os parâmetros adequados de banco de dados
- Verificar no MongoDB se os dados foram importados com sucesso.
N/A
N/A
close https://github.com/scieloorg/document-store/issues/138
N/A
=> Adiciona carga de periódicos para o MongoDB

documentstore_migracao/utils/convert_html_body.py, tests/test_convert_html_body.py
Corrige o EmptyPipe que remove tags vazias pois está removendo conteúdo além do desejado.
documentstore_migracao/utils/convert_html_body.py
tests/test_convert_html_body.py
```python setup.py test -s tests/test_convert_html_body.py```
Quando há elementos que são compostos por elementos e textos:
```xml
<root><p> texto <elemento/> texto 2</p></root>
```
```python
>>> p.text
' texto '
>>> elemento.tail
' texto 2'
>>> elemento.text
None
>>> p.remove(elemento)
>>> etree.tostring(p)
b'<p> texto </p>'
```
porque ' texto 2' é parte de elemento.
N/A
#38
https://lxml.de/api/index.html
=> Corrige o EmptyPipe que remove tags vazias

documentstore_migracao/main.py, documentstore_migracao/processing/conversion.py, documentstore_migracao/processing/pipeline.py, documentstore_migracao/utils/isis2json/isis2json.py, documentstore_migracao/utils/xylose_converter.py, tests/__init__.py, tests/test_migrate_isis.py, tests/test_xylose_converter.py
Este pull request adiciona o código necessário para realizar a importação de arquivos `json` contendo uma lista com `um` ou `mais`  fascículos.
- `documentstore_migracao/main.py` linha `181`
Para realizar testes manuais deve-se:
- Realizar a extração de uma base de fascículos no formato `MST` (anexo [1])
- Executar o comando `migrate_isis import -h`
- Configurar os parâmetros adequados de localização do arquivo `json` e parâmetros adequados para conexão com o banco de dados MongoDB.
Tomando como principio a necessidade de realizar as importações das bases ISIS, este comando concretiza a importação das bases de fascículos. O processo de importação pode ser realizado a partir do parâmetro `import` do utilitário de migração e a ajuda deve está clara o suficiente pra auxiliar nas execuções …
=> Adiciona utilitário para importar Issues

documentstore_migracao/config.py, documentstore_migracao/export/sps_package.py, documentstore_migracao/main.py, documentstore_migracao/processing/packing.py, documentstore_migracao/processing/reading.py, documentstore_migracao/processing/validation.py, documentstore_migracao/utils/convert_html_body.py, documentstore_migracao/utils/files.py, documentstore_migracao/utils/string.py, documentstore_migracao/utils/xml.py, tests/__init__.py, tests/samples/S0044-59672003000300002_sps_completo.xml, tests/samples/S0044-59672003000300002_sps_incompleto.xml, tests/samples/S0102-33062011000100002.pt.xml, tests/samples/any.xml, tests/test_processing_packing.py, tests/test_sps_package.py, tests/test_utils.py
Disponibiliza um comando para produzir os pacotes SciELO PS a partir dos XML validados, renomeando-os de acordo com as recomendações SPS. Também trocando os nomes dos ativos digitais e suas respectivas referências (xlink:href) dentro do XML. 
Os pacotes gerados por completo são gerados dentro da pasta `SPS_PKG_PATH`, dentro do subdiretório dado pelo PID. Exemplo:
```sps_packages/S0102-33062011000100002```
Os pacotes que faltam ativos digitais são movidos para dentro da pasta `INCOMPLETE_SPS_PKG_PATH`
documentstore_migracao/main.py
- ```python setup.py test -s tests/test_processing_packing.py```
- ```documentstore_migracao -p tests/samples/S0102-33062011000100002.pt.xml```
- ```documentstore_migracao -P``` (gera os pacotes de todos os XML que estiverem na pasta ```VALID_XML_PATH```)
N/A …
=> Produz de pacotes SciELO PS

.pre-commit-config.yaml, documentstore_migracao/config.py, documentstore_migracao/export/journal.py, documentstore_migracao/main.py, documentstore_migracao/processing/constructor.py, documentstore_migracao/processing/generation.py, documentstore_migracao/processing/reading.py, documentstore_migracao/utils/constructor_xml.py, documentstore_migracao/utils/string.py, tests/test_main.py, tests/test_processing.py, tests/test_utils.py
Esse PR cria um novo parametro no comando `documentstore_migracao`, que ira executar o pipeline, para adicionar a tag do `article-id` nos xmls, e também foi criado um novo `Pipeline` que esta adicionado o pid gerado através do UUID4, mas posteriormente podemos utilizar esse mesmo pipeline para outras alterações que tenham que ser feitas no xml 
pelos arquivos:
* `documentstore_migracao/processing/constructor.py`
* `documentstore_migracao/utils/constructor_xml.py`
* `documentstore_migracao/utils/string.py`
Apos atualizar o codigo, vc pode executar o comando baixo, para adicionar o pid em todos os XMLs ja convertidos e validados
```bash
$ documentstore_migracao --loglevel=info -CT
```
#29
=> Criar um "comando" para incluir PID em qualquer XML SPS

documentstore_migracao/utils/string.py, documentstore_migracao/utils/xml.py, tests/test_utils.py
Disponibiliza uma função para obter do XML a data de publicação do artigo mais precisa, considerando as várias possibilidade de combinações de datas, dando prioridade na seguinte ordem datas epub, pub, outras.
- `documentstore_migracao/utils/xml.py`
`python setup.py test -s tests/test_utils.py
`
N/A
N/A
relacionado #19 
- http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.9-branch/tagset/elemento-pub-date.html
- http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.8-branch/tagset/elemento-pub-date.html
=> Cria uma função que extrai do XML a data de publicação

documentstore_migracao/export/sps_package.py, tests/test_sps_package.py
Cria função para:
- agrupar pelos dados journal-meta, volume e issue
- ordenar uma lista de documentos XML dentro dos respectivos grupos
O parâmetro desta função corresponde a uma lista em que seus ítens são pares de (localização no kernel, xml). 
- documents_bundle_id é um artifício para agrupar os artigos, mas não significa que é o ID de nenhum Documents Bundle.
- a estratégia para ordenar é ordenar por uma tupla que é composta por:
- order
- fpage e lpage
- data de publicação do documents bundle
- data de publicação do documento
- elocation-id
- `tests/test_sps_package.py`
`python setup.py test -s tests/test_sps_package.py`
N/A
N/A
#48
N/A
=> Cria função para ordenar uma lista de documentos XML em Documents Bundles 

.gitignore, documentstore_migracao/processing/inserting.py, tests/test_inserting.py
Este PR adiciona uma função para realizar o relacionamento entre `documents bundles` e `documents`.
- `documentstore_migracao/processing/inserting.py` linha `105`
Para realizar os testes manuais deve-se:
- invocar `link_documents_bundles_with_documents` com um objeto do tipo `domain.DocumentsBundle`, uma lista contendo os `ids` de `documents` e um objeto de conexão com o banco de dados.
- Verificar se o objeto `DocumentsBundle` sofreu alterações na sua lista de `documents`
N/A
N/A
#48 
N/A
=> Adiciona função para realizar link entre documents bundles e documents

README.md, documentstore_migracao/config.py, documentstore_migracao/utils/extract_isis.py
Este PR versiona o binário do`jython` e altera a execução da extração de bases MST. A extração passa a utilizar a classe do `jython` que agora é automaticamente injetada no `CLASSPATH`.
- `documentstore_migracao/config.py` linha `63`;
- `documentstore_migracao/utils/extract_isis.py` linha `30`.
Para testar este PR deve-se:
- Verificar a não existência do `jython` no classpath antes de executar a migração:
- `echo $CLASSPATH`
- Extrair uma base MST;
- Observar se a extração ocorreu com **sucesso**
Esta modificação facilita a utilização do utilitário de migração uma vez que não é mais necessário baixar e configurar o `jython` na máquina de destino do utilitário.
N/A
N/A
[Jython bug tracker](https://bugs.jython.org/issue1422)
=> Adiciona o Jython.jar como biblioteca versionada no projeto

documentstore_migracao/utils/constructor_xml.py, documentstore_migracao/utils/manifest.py, documentstore_migracao/utils/xml.py
Altera a tag para o cielo-id, antes ela erra assim 
```
<article-id pub-id-type="scielo-id">zTp3PyKhQYvgVQdv8zkVY9h</article-id>
```
e agora é assim 
```
<article-id pub-id-type="publisher-id" specific-use="scielo">FC4vDyPznvr3yH5dsYkKm5G</article-id>
```
Devido a problemas na validação  do xml com as normas da Jats, foi necessario essa mudança
Pelo arquivo:
* `documentstore_migracao/utils/constructor_xml.py`
Apos atualizar o codigo, rodar novamente a construção dos XML para que seja adiciona a nova tag nos XMLs 
#60
=> Atualizacao da tag do scielo-id

documentstore_migracao/export/article.py, documentstore_migracao/export/journal.py, documentstore_migracao/processing/packing.py, documentstore_migracao/utils/request.py, tests/test_export.py, tests/test_processing_packing.py, tests/test_utils.py
Trata exceções decorrentes da comunicação com o Article Meta. O comportamento do `utils.request.get()` foi alterado, além dos pontos da aplicação que o utilizam. A exceção lançada pela função, `HTTPGetError`, deve ser tratada por quem a utiliza.
Em `documentstore_migracao/utils/request.py`.
Executando o comando `SCIELO_COLLECTION=scl documentstore_migracao --issn-journal 0066-782X`, apesar dos erros que ocorrem, o processo de extração não deve ser interrompido.
Detalhes no ticket #51.
N/A.
#51.
Nenhuma.
=> Trata exceções decorrentes da comunicação com o Article Meta

documentstore_migracao/utils/manifest.py
Corrige função `manifest.get_document_bundle_manifest()` na definição da data de criação, que utiliza `xylose_converter.parse_date`. Como a data de publicação do documento de `SPS_Package` retornar uma tupla com os dados da data, este monta a data em formato string para o parser.
Esta correção é importante pois o erro impede a importação dos documentos para o Kernel.
Em `documentstore_migracao/utils/manifest.py`, L23.
Executando o comando `ds_migracao import` com pacotes válidos, a importação dos documentos no kernel deve ocorrer sem problemas. 
Foram feitas alterações na data de publicação do documento de `SPS_Package` e faltou alterar esta parte do fluxo da migração.
N/A.
Nenhum.
Nenhuma.
=> Corrige get_document_bundle_manifest() na definição da data de criação

documentstore_migracao/processing/validation.py, tests/test_processing.py
Durante a validação de artigos com `nós` contendo identificadores duplicados o parser do LXML lança uma `Exception` do tipo `etree.XMLSyntaxError`, o `packtools` não trata este tipo de erro consequentemente a execução da migração era encerrada abruptamente.
- `documentstore_migracao/processing/validation.py` linha `21`
Para testar manualmente este PR, deve-se:
- Baixar o arquivo [1];
- Executar o comando `ds_migracao validate --file path/para/o/arquivo.txt`;
- Observar que a execução quebra e o programa finaliza a sua execução do modo esperado.
N/A
N/A
closes #50 
[already_id.txt](https://github.com/scieloorg/document-store-migracao/files/3158776/already_id.txt)
[lmlx execeptions](https://lxml.de/api/lxml.etree.XMLSyntaxError-class.html)
=> Trata erros do LXML durante a validação de artigos

documentstore_migracao/utils/convert_html_body.py, tests/test_convert_html_body.py
Corrige a conversao da tag email a partir de a href=mailto:, considerando as várias possiblidades, documentadas no #75
- `tests/test_convert_html_body.py:370`
- `python setup.py test -s tests/test_convert_html_body.py`
Os testes e o #75 indicam os casos possíveis de conversão.
N/A
#75
N/A
=> Corrige a conversao da tag email a partir de a href=mailto:

documentstore_migracao/config.py, documentstore_migracao/export/sps_package.py, documentstore_migracao/processing/conversion.py, requirements.txt, tests/test_processing.py, tests/test_sps_package.py
Altera o módulo de conversão para gerar XMLs com `specific-use="sps-1.9"` e efetua as
adaptações da tag `pub-date` para a nova versão.
Para a validação, também atualiza a versão do Packtools.
Em `documentstore_migracao/processing/conversion.py`, L20.
Em `documentstore_migracao/export/sps_package.py`, L410.
Com XMLs já extraídos do Article Meta, executar o comando `SCIELO_COLLECTION=scl ds_migracao convert`. Os XMLs convertidos devem estar com `specific-use="sps-1.9"` e com `pub-date` de acordo com a especificação nova.
Nenhum.
N/A
#92 
__What's new SPS 1.9__:
https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/latest/whatsnew-1.9.html
__Documentação de `<pub-date>`__
https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-pub-date.html …
=> Altera conversão para tratar as alterações no pub-date na SPS 1.9

documentstore_migracao/config.py, documentstore_migracao/export/article.py, documentstore_migracao/processing/extracted.py, documentstore_migracao/utils/files.py, requirements.txt
Este pull request adiciona o mecanismo para que durante a extração de artigos seja possível **parar** e **continuar** do mesmo ponto. Também adiciona o conceito de tentativas em decorrência de falhas relacionadas ao uso do HTTP durante a extração de artigos.
- `documentstore_migracao/utils/files.py` linhas `108:162`
- `documentstore_migracao/processing/extracted.py` linha `17`
Para testar manualmente este PR deve-se:
- Iniciar a extração de uma lista de pids
- Interromper a extração em algum ponto ao seu critério
- Executar a extração novamente
- A extração deve `continuar` de onde `parou`
---
- Iniciar a extração de uma lista de pids com loglevel `INFO`
- Causar instabilidades de conexão relacionadas com o `article meta`
- Observar as tentativas de obtenção do mesmo artigo algumas vezes …
=> Aumenta a resistência a falhas durante a extração de artigos

documentstore_migracao/export/sps_package.py, documentstore_migracao/utils/convert_html_body.py, documentstore_migracao/utils/xml.py, tests/test_convert_html_body.py, tests/test_data_sanitization.py, tests/test_utils.py
Esse PR, cria um novo Pipeline para tratar caso a caso a conversão das tag do body dos arquivos XMLs e reorganiza as tarefas do pipeline atual
pelo arquivos:
* `documentstore_migracao/export/sps_package.py`
* `documentstore_migracao/utils/xml.py`
Rodando os comando de conversao e validação
```
$ ds_migracao convert && ds_migracao validate
```
#73 #105 #113 #112 #106
=> Correção dos primeiros casos da conversão do XML  #73

documentstore_migracao/utils/convert_html_body.py, tests/test_convert_html_body.py, tests/test_data_sanitization.py
Esse PR, remove tags `a` que possuam ids duplicados no xmls 
Pelos arquivos:
*  `tests/test_convert_html_body.py`
Rodando os comando de conversao e validação
```
$ ds_migracao convert && ds_migracao validate
```
#115
=> [conversao] Remover a tag 'a' com id duplicados

documentstore_migracao/config.py, documentstore_migracao/main/migrate_articlemeta.py, documentstore_migracao/utils/build_ps_package.py, requirements.txt
Esse PR tem com objetivo produzir os pacotes SPS a partir da estrutura do Site SciELO.
Para validar esse PR é possível revisando os módulos: 
- documentstore_migracao/utils/build_ps_package.py
- documentstore_migracao/main/migrate_articlemeta.py 
- documentstore_migracao/config.py
Montando as pastas compartilhadas da rede para a estrutura do Site de Homologação: 
sudo mount -t nfs -o nfsvers=4 <IP>:/var/www/scielo_br/bases/xml data/xml
sudo mount -t nfs -o nfsvers=4 <IP>:/var/www/scielo_br/bases/pdf data/pdf
sudo mount -t nfs -o nfsvers=4 <IP>:/var/www/scielo_br/htdocs/img/revistas data/img
Commando para teste: **ds_migracao pack_from_site -a rsp -Xfolder data/xml -Ifolder data/img -Pfolder data/pdf**
OBS: Caso necessário para roda posso informar de forma privada o endereço IP.
Para …
=> Adiciona a capacidade de coletar os XMLs, PDFs e IMGs da estrutura de pasta do Site antigo do SciELO

documentstore_migracao/utils/convert_html_body.py, tests/test_convert_html_body.py
Esse PR cria um novo pipeline para a tag `disp-quote` que visa implementar a correção para o problema reportado pelo ticker #108 
Pelo arquivos
* `tests/test_convert_html_body.py`
```
$ python setup.py test -s tests.test_convert_html_body.TestHTML2SPSPipeline
```
#108
=> Adicionar o pipe para tratar a Tag disp-quote #108

documentstore_migracao/utils/xml.py, tests/test_utils.py
Esse PR corrige o problema em https://github.com/scieloorg/document-store-migracao/issues/68#issuecomment-491956421, e que deu origem ao ticket #121, visando assim declarar a codificação padrão dos XMLs convertidos e resolver o problema relatado 
pelo arquivo: 
* `documentstore_migracao/utils/xml.py`
Apos atualizar o codigo, e rodar o comando de conversão `ds_migracao convert` deve notar na analize dos xmls contidos na pasta `xml/conversion/` que em seu cabeçalho se encontra encode `utf-8`, ex:
```xml
<?xml version='1.0' encoding='utf-8'?>
```
#121
=> Adiciona o encoding na conversão dos xmls

documentstore_migracao/utils/convert_html_body.py, setup.py, tests/test_convert_html_body.py
Cria elementos table-wrap, fig, disp-formula, fn, respectivos xref. Estes elementos são criados a partir de a[@name], a[@id], a[@href] e img[@src] que são dos ativos digitais, a[@href] que são links internos.
- tests/test_convert_html_body.py
- documentstore_migracao/utils/convert_html_body.py
```
self.CompleteAnchorPipe(super_obj=self),
self.InternalLinkAsAsteriskPipe(super_obj=self),
self.AnchorAndInternalLinkPipe(super_obj=self),
self.AssetsPipe(super_obj=self),
```
```
class AssetsPipeline(object):
def __init__(self, pid, index_body=1):
self.pid = pid
self.index_body = index_body
self._ppl = plumber.Pipeline(
self.SetupPipe(),
self.AddAssetInfoToTablePipe(super_obj=self),
self.AddAssetInfoToImgElementsPipe(super_obj=self),
self.AddAssetInfoToLinkElementsPipe(super_obj=self), …
```
=> Cria elementos table-wrap, fig, disp-formula, fn, respectivos xref

documentstore_migracao/utils/convert_html_body.py, tests/test_convert_html_body.py, tests/test_data_sanitization.py
Esse PR implementa os pipelines necessários para fazer a conversão de tags conforme descrito no Ticket #107 
Pelos arquivos
* `tests/test_convert_html_body.py`
* `tests/test_data_sanitization.py`
```
$ python setup.py test -s tests.test_convert_html_body
```
fix #107
=> Pipeline para converter as tags para def-list, def-items,

documentstore_migracao/main/migrate_articlemeta.py, documentstore_migracao/processing/inserting.py, tests/test_inserting.py, tests/test_migrate_articlemeta.py
Este PR altera a ferramenta de linha de comando utilizada para importar os pacotes SPS. As alterações são elencadas da seguinte maneira:
1) Possibilita o uso do argumento `--folder` para determinarmos qual pasta deve ser
utilizada para realizar a importação dos pacotes SPS.
1.1) A pasta padrão é a definida pela variável de ambiente `SPS_PKG_PATH`.
1.2) Agora é possível importar um único pacote SPS por meio do parâmetro `--folder`.
2) Altera a função `register_documents` para buscar os pacotes SPS em níveis hierárquicos
não definidos.
2.1) Os pacotes SPS montados a partir de documentos HTML possuem apenas um nível de pastas `pid/documento`.
2.2) Os pacotes SPS montados a partir do filesystem possuem 3 níveis de pastas.
- `documentstore_migracao/main/migrate_articlemeta.py` L: `139`
Para …
=> Possibilita a importação de pacotes nativos

documentstore_migracao/export/sps_package.py, documentstore_migracao/processing/conversion.py, tests/test_sps_package.py
Esse PR Implementa a contagem e a marcação no XML da quantidade de elementos `fig`, `table` e `equation` presentes em todos os `bodys` do XML
Pelos Arquivos
* `documentstore_migracao/export/sps_package.py`
* `tests/test_sps_package.py`
Pelo comando de test do utilitario
```shell
$ python setup.py test -s tests.test_sps_package.Test_ArticleMetaCount
```
Pelo processo de conversão, que apos executar o comando de  conversão `ds_migracao convert`, verifique abrindo um xml convertido que no bloco tags `<counts />` deve ser apresentado algo como o exemplo abaixo:
```xml
<counts>
<fig-count count="4"/>
<table-count count="2"/>
<equation-count count="0"/>
<ref-count count="55"/>
<page-count count="10"/>
</counts>
```
#131 
https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/lates …
=> Adição da contagem de fig, table e equation nos XML convertidos

documentstore_migracao/__init__.py, documentstore_migracao/export/article.py, documentstore_migracao/export/sps_package.py, documentstore_migracao/processing/packing.py, documentstore_migracao/utils/convert_html_body.py, tests/test_processing_packing.py
Esse PR implementa a logica de baixar os PDF dos pacotes SPS dos artigos extraidos do `AM` e convertido para `XML` como descrito no TK #93, e tambem corrige o Bug de `Segmentation fault` que acontecia durante a conversão dos XMLs
Pelos arqtivos:
* `documentstore_migracao/export/sps_package.py`
* `documentstore_migracao/export/article.py`
* `documentstore_migracao/processing/packing.py`
* `tests/test_processing_packing.py`
FIX `Segmentation fault`
* `documentstore_migracao/__init__.py`
Apos os comandos de `extract` -> `convert` -> `validate` execute o comando de `pack`
```
$  ds_migracao pack
```
e apos o processo verifique que nos pacotes SPS dentro da pasta `xml/sps_packages/<PID>/` encontrasse também os `PDF` e mídias digitais 
#93
=> Incluir os PDFs do documento no seu pacote SciELO PS

documentstore_migracao/config.py, documentstore_migracao/main/__init__.py, documentstore_migracao/processing/extracted.py
Acelera em até 20x a obtenção dos documentos XML a partir do ArticleMeta, com o uso de concorrência.
Pelo módulo `processing/extracted.py`
Execute o comando `ds_migracao extract` antes e depois da aplicação do patch.
A nova implementação trata `SIGINT` de forma a mitigar a perda de dados. Para isso o programa aguarda que todas as threads em execução sejam finalizadas antes de terminar, o que pode levar alguns vários segundos.
n/a
n/a
n/a
=> Torna assíncrona a obtenção dos documentos em XML

documentstore_migracao/utils/convert_html_body.py, documentstore_migracao/utils/string.py, documentstore_migracao/utils/xml.py, tests/test_convert_html_body.py, tests/test_utils.py
Corrige os caracteres acentuados no XML que estão sendo convertido a entidades. Por exemplo, &amp;#x27; ao invés de ser representado por seu caracter, sendo que o original é um caracter. 
Foi removido o pipe: HTMLEscapingPipe. No entanto, não foi substituído pelo pipe xml.sax.saxutils.escape pois não encontrei o caso de uso para o pipe HTMLEscapingPipe.
Foi identificado um problema na função string.normalize() por usar unicodedata.normalize() alterava a codificação dos caracteres, decompondo os caracteres acentuados, por exemplo, é era convertido a e '.
documentstore_migracao/utils/string.py:7
python setup.py test -s tests.test_convert_html_body.Test_HTML2SPSPipeline 
n/a
n/a
#146 
n/a
=> Corrige os caracteres acentuados no XML que estão sendo convertido a entidades

documentstore_migracao/processing/inserting.py, documentstore_migracao/utils/logger.py, tests/test_inserting.py
Corrige o bug reportado pelo issue #159, 
**obs**: foi aplicado o black nos arquivos modificados, por isso as modificações foram maiores do que a necessidade para a correção do BUG
pelo arquivos:
* `documentstore_migracao/processing/inserting.py`
```shell
$ python setup.py test -s tests.test_inserting.TestProcessingInserting
```
Esse erro é pertinente pois ao o padrão do valor da chave `entity` no `dict` de _changes do kernel_ deve ser igual ao nome da classe que ele representa
#159
=> Fix bug #159 Entidade "Journal" grafada de maneira errada

documentstore_migracao/processing/packing.py, tests/test_processing_packing.py
Resolve bug que causava erro ao tentar produzir uma URL com algum segmento inválido.
documentstore_migracao/processing/packing.py:64
```bash
python setup.py test
```
n/a
n/a
#158 
n/a
=> Resolve bug na produção da URL quando há segmentos inválidos

documentstore_migracao/main/tools.py, documentstore_migracao/tools/constructor.py, tests/test_tools.py
Esse PR altera os o comando `ds_tools construction` para que seja possível ler uma pasta com varios sub-niveis e permite que seja possível alterar o proprio local do xml, e adicionar o scielo_id, e depois é possivel gerar o zip para o processamento do airflow
Pelos arquivos:
* `documentstore_migracao/main/tools.py`
* `documentstore_migracao/tools/constructor.py`
* `tests/test_tools.py`
Pelos teste unitarios:
```
$ python setup.py test
```
ou 
Executando o utilitario de migração e verificando se os xmls gerado contem o  `scielo_id`
```
$ ds_tools construction -p ./xml/site_sps_packages/csp --in-place=true
```
Essa alterações se deram para ser um complemento do comando `ds_migracao pack_from_site` e que apos coletar os xmls nativos, seja adicionado o `scielo_id` na propria estrutura de …
=> Adição de parâmetro para gerar scielo_id

documentstore_migracao/utils/xylose_converter.py, tests/__init__.py, tests/test_xylose_converter.py
Esse PR implementa o campo `publication_months` definido pelo scieloorg/document-store#159 e remove o campo `publication_month` e `publication_season` ja que não são mais utilizados
Pelos arquivos
* `documentstore_migracao/utils/xylose_converter.py`
* `tests/test_xylose_converter.py`
```
$ python setup.py test
```
A estrutura desse campo foi definida em farias reuniões com o time de devs e com pessoas das areas de publicão de conteúdo, e para mais informações consultar os tickets e os comentarios atrelados no PR
N/A
#170 
#172
=> Adicionar `publication_months` e remoção do Remover mês de publicação

documentstore_migracao/export/sps_package.py
Esse PR corrige a dependencia do `acron` para o caminho do ativo digital no **Min.io**
Para mais detalhes TK #137 
Pelo Arquivo
* `documentstore_migracao/export/sps_package.py`
Reproduzir os passo citados no Ticket
>### Passos para reproduzir o problema
> 1. Extraia artigos da revista RSP via comando `pack_from_site`;
> 2. Aguarde a extração de um artigo que não possua o acrônimo do Periódico, ex: `S0034-8910.2013047003868`;
> 3. Realize a importação dos pacotes SPS;
> 4. Observe um erro relacionado ao uso do `acron` (`documentstore_migracao/export/sps_package.py` L: `228`)
> 5. Observe que no `Minio` o prefixo de bucket criado é o `1518-8787_None`;
Essa correção utiliza a mesma tecnica de implementação que a utilizada no `opac-airflow`
N/A
#137 …
=> Fix em Crash pela falta de acrônimo

documentstore_migracao/export/sps_package.py, documentstore_migracao/object_store/minio.py, documentstore_migracao/processing/inserting.py, documentstore_migracao/processing/packing.py, documentstore_migracao/utils/build_ps_package.py, tests/test_inserting.py, tests/test_processing_packing.py, tests/test_sps_package.py
Este PR altera empacotamento para obter URLs legadas das manifestações de documentos 
e respectivos idiomas e registra essas URLs junto com o objeto no Object Store.
Foram alterados os empacotamentos de documentos HTML e XML nativos para gerar um arquivo 
JSON `manifest.json` com as URLs legadas das manifestações e respectivos idiomas.
Para os artigos HTML, estes dados são obtidos do Article Meta, enquanto para os XMLs 
nativos, as URLs são inferidas através das manifestações do pacote e os idiomas do XML.
Na importação, tenta ler o arquivo `manifest.json` do pacote do documento. Em caso de 
sucesso, tentará associar as manifestações à sua URL legada e registrá-la no `metadata` 
do objeto no Object Store (Minio). Também melhora a detecção do idioma da manifestação.
É recomendado que a …
=> Detecta idioma correto dos PDFs na importação dos pacotes

documentstore_migracao/utils/convert_html_body.py, tests/test_convert_html_body.py
Até então, a inserção de conteúdos externos provenientes de HTML mencionados no body, eram tratados em um pipe no meio do processo e as conversões eram aplicadas pontualmente neste HTML importado. Mas o problema é que tratar estes trechos de HTML isoladamente é ruim já que o trecho faz parte do body, não é um trecho isolado. Há links para dentro do conteúdo dos HTML externos. Sendo assim, o ideal é inserir todos os HTML externos dentro do body e assim tratá-lo de uma só vez como um todo.
Então, este código, no início da conversão, localiza os padrões: `<a href="/img/revistas/acron/volumenumero/html/file.htm"/>` e  `<a href="/img/revistas/acron/volumenumero/img.gif"/>` os converte por referências internas.
- faz a importação do conteúdo de HTML mencionado no body, importando todos os HTML, …
=> [dsm][conversao][154]Muda a estratégia quanto à importação do conteúdo de HTML referenciados

documentstore_migracao/utils/convert_html_body.py, tests/test_convert_html_body.py
Gera o ID e RID no final da conversão, pois fazer a alteração prematuramente atrapalha a correspondência entre os elementos
documentstore_migracao/utils/convert_html_body.py L:147
`python setup.py test`
n/a
n/a
Contribui na solução de #154
n/a
=> [dsm][conversao][154-02]Gera o ID e RID no final da conversão, pois fazer a alteração dos IDs

documentstore_migracao/utils/xylose_converter.py, tests/test_xylose_converter.py
Este PR adequa conteúdo das subject areas ao esperado pelo domínio do Kernel. Foi removida a transformação para caixa alta.
- `documentstore_migracao/utils/xylose_converter.py` L: `115`
Para testar este PR deve-se:
- Realizar a migração da base `title`;
- Iniciar uma instância do Kernel;
- Acessar um `journal` migrado;
- Observar a propriedade `subject_areas` e seu conteúdo sem transformações de caixa alta.
N/A
N/A
#185 
N/A
=> Adequa subject areas ao padrão do Kernel

documentstore_migracao/utils/convert_html_body.py, documentstore_migracao/utils/convert_html_body_inferer.py, tests/test_convert_html_body.py
inferir os elementos aos quais serão convertidos
Acrescenta atributos name, id, xml_text, nos elementos A que ajudarão a inferir os elementos aos quais serão convertidos
documentstore_migracao/utils/convert_html_body.py Linha: 1068
`python setup.py test`
n/a
n/a
Contribui na solução de #154 
n/a
=> [dsm][conversao][154-03] Acrescenta atributos name, id, xml_text, nos elementos A que ajudarão a

.travis.yml, documentstore_migracao/config.py, documentstore_migracao/utils/convert_html_body.txt, documentstore_migracao/utils/convert_html_body_inferer.py, requirements.txt, setup.py, tests/test_convert_html_body.py
Aprimora e otimiza o Inferidor. Acrescenta novos prefixos e tags. Otimiza a busca de prefixo e/ou tag. Ajustes no algoritmo para inferir os dados de conversão.
documentstore_migracao/utils/convert_html_body_inferer.py
`python setup.py test -s tests.test_convert_html_body.TestDeduceAndSuggestConversionPipe`
n/a
n/a
Contribui na solução de #154 aprimorando a inferência do elemento ao qual deve ser convertido o a[@name] e/ou a[@href].
n/a
=> [dsm][conversao][154-04] Aprimora e otimiza o Inferidor

documentstore_migracao/processing/conversion.py, documentstore_migracao/utils/convert_html_body.py, tests/test_convert_html_body.py
Resolve alguns problemas de PR relacionados com os #154:
1. Tenta baixar o arquivo HTML apenas 1 vez, caso não encontra o HTML, registra no log que houve falha e que é necessário ação manual, o `<a href=""/>` gerará um link externo.  Também melhora o nome de alguns atributos.
2. Resolve bug em CompleteElementAWithXMLTextPipe
3. Resolve problema de segment fault que surge após a incorporação do PR #189, no entanto, este problema não aconteceria se todos os PR que resolvem o issue #154 fosse incorporados.
4. Corrige a get_node_text para não retornar texto de comentário
Revisar por commmit:
1. documentstore_migracao/utils/convert_html_body.py L: 2167
2. documentstore_migracao/utils/convert_html_body.py L:1415
3. documentstore_migracao/utils/convert_html_body.py L:1829
4. …
=> Resolve alguns problemas de PR relacionados com os #154

documentstore_migracao/utils/convert_html_body.py, requirements.txt, setup.py, tests/test_convert_html_body.py
Finaliza a refatoração das conversões relacionadas com os elementos `a[@href]` e `a[@name]` que geram ativos digitais e notas de rodapé (app, fig, table-wrap, disp-formula, fn), mas especificamente a de "fn"
Revisar por commit
Executando o comando:
`ds_migracao convert --file xml/source/<pid>.xml`
e visualizando o resultado em xml/conversion/
e/ou executando:
`ds_migracao validate`
para visualizar os erros
Erros que permanacem ainda de uma amostra de 3435 documentos XML: 
**app content does not follow the DTD**                                                    
- S0034-89101973000100001.err
- S0085-56262008000300005.err
- S0101-41612005000300005.err
- S0103-166X2005000300005.err
- S0103-17592008000300005.err
- S0104-40362013000300005.err
- S1807-76922008000300005.err
**fig content does …
=> [dsm][conversao] Resolve a conversão de notas de rodapé

documentstore_migracao/export/sps_package.py, documentstore_migracao/main/migrate_articlemeta.py, documentstore_migracao/utils/build_ps_package.py, tests/apptesting.py, tests/test_build_ps_package.py, tests/test_sps_package.py, tests/utils.py
Adiciona atualização de arquivos XMLs nativos com dados da base artigo, lidas de um arquivo CSV. Caso os XMLs não tenham um dos dados que estão no CSV, o conteúdo é atualizado no arquivo copiado do diretório informado.
Os seguintes dados são esperados no CSV:
- PID
- PID AOP
- FILE
- DATA (COLLECTION)
- DATA PRIMEIRO PROCESSAMENTO
- DATA DO ULTIMO PROCESSAMENTO
É importante salientar que os dados presentes no XML nativo não são sobrescritos.
É recomendado que a revisão do PR seja feita por commits.
1. Selecione um periódico com XMLs que tenham dados a serem complementados
2. Execute o comando `ds_migracao pack_from_site`, informando o acrônimo do periódico selecionado e a opção `-Article-csvfile` com o path para o arquivo CSV contendo os dados de artigos. Ex.:
`ds_migracao pack_from_site …
=> Adiciona atualização de arquivos XMLs nativos com dados da base artigo (em CSV)

documentstore_migracao/utils/convert_html_body.py, tests/test_convert_html_body.py
Converte `a[@href]`, cujo conteúdo contém uri com formato não esperado, para `<ext-link/>`.
```xml
<a href="http//sisifo.fpce.ul.pt" target="_blank" link-type="unknown" xml_text="http//sisifo.fpce.ul.pt">http//sisifo.fpce.ul.pt</a>
<a href="http//www.socerj.org.br/temas/21enfer.pdf" target="_blank" link-type="unknown" xml_text="http//www.socerj.org.br/temas/21 enfer.pdf">http//www.socerj.org.br/temas/21 enfer.pdf</a> - url incorreta
<a href="http//www.books.nap.edu/books/0309071836/html/287.html#pagetop" link-type="external" xml_text="http//www.books.nap.edu/books/0309071836/html/287.html#pagetop">http//www.books.nap.edu/books/0309071836/html/287.html#pagetop</a>
<a href="http//www.banet.com.br/propQstalABMR.htm" target="_blank" link-type="external" …
```
=> Considera outros formatos de valor de `a[@href]` para gerar `ext-link`

documentstore_migracao/processing/inserting.py, documentstore_migracao/processing/pipeline.py, documentstore_migracao/utils/__init__.py, tests/test_inserting.py, tests/test_migrate_isis.py
Este PR compatibiliza o utilitário de migração com a mudança https://github.com/scieloorg/kernel/pull/191, do Kernel.
Além da compatibilização também foram feitas mudanças com o objetivo de melhorar o código, como refatoração, reorganização dos imports, renomeação de variáveis e aplicação de formatação automática com [black](https://pypi.org/project/black/). Deixei cada passo em _commits_ separados para que seja possível seguir a sequência de atividades que foram realizadas.
As alterações se concentram nos módulos `processing.pipeline` e `processing.inserting`. Sugiro seguir os _commits_ em ordem crescente.
Você terá que de fato migrar e importar bases de dados ISIS e documentos para uma instância do Kernel.
Para migrar bases ISIS (assumindo um MongoDB rodando em localhost:27017):
1. …
=> Armazena o conteúdo modificado junto do registro de mudança

documentstore_migracao/export/sps_package.py, documentstore_migracao/processing/conversion.py, tests/test_processing.py, tests/test_sps_package.py
Este PR adiciona mais um método ao SPS_Package para fazer transformações no conteúdo do XML não atendidas na transformação do conteúdo do `body`. Foi movida a chamada da transformação do pub-date para este método, além da inclusão do método que move os grupos de anexos/apêndices do `body` para o `back` e, assim, tornar o XML válido com relação a essas tags em específico.
Em `documentstore_migracao/export/sps_package.py`, L534.
Rodando os testes:
```python setup.py test```
OU
- Extraia algum artigo em HTML com o comando `ds_migracao extract`
- Perceba que o `body` tem tags `<app-group>`
- Converta o XML gravado na extração com o comando `ds_migracao convert`
- Verifique o XML gerado em `xml/conversion/`
- As tags `<app-group>` devem estar no `back` e não mais no `body`, após as …
=> Move app-group do body para o back durante a conversão

documentstore_migracao/utils/convert_html_body.py
Corrige o caminho das imagens
```html
<a href="../img/revistas/pd/v31n3/a05tab01.jpg">Table 1</a>
<a href="../img/revistas/si/v19n3/a05fig01.jpg">Figura 1</a>
<a href="..img/a05tab04.jpg" link-type="external"/>
```
`documentstore_migracao/utils/convert_html_body.py`
`ds_migracao convert --file xml/source/S0104-92242014000300005.xml`
n/a
n/a
#212
n/a
=> Corrige os caminhos das imagens relacionadas como /img/revistas

documentstore_migracao/utils/convert_html_body.py
Remove as aspas de dentro do conteúdo de a[@href]
```html
<a href="#&quot;fig06&quot;" link-type="internal"><bold>Figure 6A</bold></a>
```
se remover `&quot;` possivelmente fará match com o `<fig id="fig06"/>` então automaticamente será convertido para `<xref/>`
`documentstore_migracao/utils/convert_html_body.py
`
`ds_migracao convert --file xml/source/S1676-24442013000300005.xml`
`vi xml/conversion/S1676-24442013000300005.en.xml`
buscar por fig06.
n/a
n/a
#213, parte de #205
n/a
=> Remover as aspas de dentro de a[@href]

documentstore_migracao/export/sps_package.py, documentstore_migracao/main/migrate_articlemeta.py, documentstore_migracao/processing/pipeline.py, documentstore_migracao/utils/extract_isis.py, documentstore_migracao/utils/xml.py, tests/test_migrate_isis.py, tests/test_sps_package.py, tests/test_utils.py
Adiciona o comando para atualizar as `mixed-citations` de um ou mais arquivos `xml` utilizando uma ou mais bases `mst`.
- `documentstore_migracao/main/migrate_articlemeta.py` L: `271`
Para testar este pull request manualmente deve-se:
- Extrair documentos (lista de exemplo em [1]);
- Obter a base MST necessária para extrair os parágrafos dos documentos (exemplo em [2]);
- Executar o comando para atualização das citações (ajuda em: `ds_migracao mixed-citations -h`)
O código atual trabalha de forma linear, os xmls serão processados um a um. Para a atualização do XML é necessário executar o processo de `isis2json` com o `jysthon` (por enquanto). Se a atualização utilizar os parágrafos no estilo SciELO BR (`bases/artigo/p/*`) teremos uma lentidão visível uma vez que para cada base `mst` lida …
=> Adiciona processo para inclusão das mixed-citations

documentstore_migracao/utils/xylose_converter.py, tests/test_xylose_converter.py
Migra os dados de "publisher" (responsável pelo periódico) da base title (isis) para o kernel no campo "institution_responsible_for"
Os dados são: nome, endereço, cidade, estado e país
documentstore_migracao/utils/xylose_converter.py
n/a
n/a
n/a
https://github.com/scieloorg/opac/issues/1453
n/a
=> Migra os dados de "publisher" do isis para kernel

documentstore_migracao/utils/convert_html_body.py, tests/test_convert_html_body.py
Garante que o conteúdo de arquivos mencionados (html e imagens) esteja presente apenas 1 vez e que seja a primeira menção.
O problema que ocorria é que uma imagem estava contida em um html mencionado e também havia uma menção diretamente ao arquivo de imagem.
http://www.scielo.br/img/revistas/dados/v52n3/05t08.gif
Está contida em:
http://www.scielo.br/img/revistas/dados/v52n3/html/05t08.htm
```html
<body>
<p>
<font>
<b>c) Percepção    sobre deveres e direitos relativos ao exercício da cidadania</b></font></p>
<p>
<font size="2" face="Verdana, Arial, Helvetica, sans-serif">
Quando analisamos    as opiniões em torno dos deveres relacionados ao bom exercício
da cidadania, podemos perceber a tendência de os brasileiros valorizarem,    
pelo menos no plano discursivo, práticas comumente …
```
=> [dsm][conversao] Garante que o conteúdo de arquivos mencionados (html e imagens) esteja presente apenas 1 vez

documentstore_migracao/export/sps_package.py, documentstore_migracao/utils/convert_html_body.py, tests/test_convert_html_body.py, tests/test_sps_package.py
Remove do body os parágrafos correspondentes às referências
Revisar pelos commits
`ds_migracao convert --file xml/source/S1516-14391999000300005.xml`
referências são removidas
`ds_migracao convert --file xml/source/S1516-31802007000300005.xml`
referências são mantidas
Para carregar na base de dados os artigos (HTML), eram usados dois arquivos: body e markup. O body continha apenas HTML e o markup continha HTML+SGML. O Converter usava o arquivo markup com as referências marcadas para localizar o parágrafo correspondente à referência no arquivo body. As referências localizadas no body são indicadas com ``. Mas nem todas as referências marcadas são necessariamente localizadas no body.
n/a
#231
n/a
=> Remove do body os parágrafos correspondentes às referências

documentstore_migracao/utils/convert_html_body.py, tests/test_convert_html_body.py
A conversão, antes da correção, considerava que os `a[@href]` que apareciam depois do seu correspondente `a[@name]` poderiam ser indicativos de ser "label" de nota de rodapé, mas ao comprovar que não eram labels, eram considerados como links inválidos e, por isso, eram apagados ao invés de gerarem `<xref/>`.
Com a correção, a ordem de apresentação de `a[@href]` e de seu correspondente `a[@name]` deixa de ser relevante. O que é usado para detectar se é ou não label de nota de rodapé é o conteúdo do `a/@xml_text`
Por commits.
`ds_migracao convert --file xml/source/S1519-70772013000300005.xml`
n/a
n/a
#227
n/a
=> Corrige a conversão de a[@href] que eram apagados ao invés de gerarem elementos <xref/>

documentstore_migracao/utils/convert_html_body.py, tests/test_convert_html_body.py
A conversão de fig ou table-wrap estava errada quando as imagens (thumbnail) estavam no HTML original dentro de table de HTML para estabelecer um layout em particular.
por commits
Executando `ds_migracao convert`
Em anexo estão os PIDs, classificados pelo tipo de layout no html.
[created-from-layout.zip](https://github.com/scieloorg/document-store-migracao/files/4042392/created-from-layout.zip)
n/a
n/a
#238
n/a
=> [dsm][conversao] Corrige fig (e table-wrap) quando no HTML original usava "<table>" no layout

documentstore_migracao/export/sps_package.py, documentstore_migracao/processing/conversion.py, tests/test_sps_package.py
Este pull request adiciona a capacidade de remover o corpo do documento quando:
1) O documento possuir ao menos uma tag `self-uri` apontando para a versão em `pdf`;
2) O `body` do documento existir apenas para referenciar as versões do texto completo em `pdf`.
- `documentstore_migracao/export/sps_package.py` L: `559`
- Extrair documentos que possuem o corpo apenas para referenciar o texto completo em PDF (ou usar o anexo [1]);
- Converter os arquivos (`ds_migracao convert`)
- Verificar que o corpo dos documentos com tags `self-uri` foi removido;
- Verificar que o corpo de documentos sem tags `self-uri` foi mentido;
N/A
N/A
#206 
N/A
[[1] - Pasta source com documentos com e sem self-uri](https://drive.google.com/open?id=1O1Gwannoq36_2SPsXp …
=> Remove `body` que faz referência ao texto completo em PDF

documentstore_migracao/processing/inserting.py, documentstore_migracao/utils/__init__.py
Este pull request adiciona o registro de mudanças para os renditions importados durante a migração. 
- `documentstore_migracao/utils/__init__.py` L:`4`
Para testar este pr manualmente, deve-se:
- Realizar as etapas de extração, conversão e importação de um pacote SPS;
- Verificar a API de mudanças do `kernel` se foi adicionado o registro de mudanças para os renditions do pacote.
Este pr faz uso da [interface de domínio criada](https://github.com/scieloorg/kernel/blob/master/documentstore/services.py#L480) no `kernel` para serializar corretamente os dados da manifestação que está associada ao documento, sendo assim é preciso atualizar a versão do `scielo-kernel` para utilizar este código.
N/A
closes #237
N/A
=> Registra mudança para os renditions importados

documentstore_migracao/utils/convert_html_body.py, tests/test_convert_html_body.py
Corrige a identificação de uma tabela, garantindo que a tabela estaja no mesmo nível do `table-wrap`
Rodando os testes automáticos e ou executando manualmente com o arquivo que utilizamos como exemplo no tíquete #246 
Executando o seguinte comando: 
```shell 
ds_migracao convert --file S0100-879X1997000300001.xml
```
Artigo que estamos utilizando como exemplo: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0100-879X1997000300001
N/A
Resultado final das tabelas: 
#246 
N/A
=> Ajusta o alinhamento de table com table-wrap e ajusta label da tabela

documentstore_migracao/export/article.py, documentstore_migracao/export/sps_package.py, documentstore_migracao/processing/conversion.py, documentstore_migracao/processing/extracted.py, documentstore_migracao/utils/xylose_converter.py, requirements.txt, tests/samples/S0036-36341997000100001.json, tests/test_conversion.py, tests/test_export.py, tests/test_processing.py, tests/test_sps_package.py, tests/test_xylose_converter.py
Este PR completa datas de publicação dos documentos provenientes de HTML com os metadados extraídos do Article Meta. Assim como o XML SPS, os metadados são extraídos do Article Meta e salvos em um arquivo JSON junto com o XML. Na etapa de conversão, após a adaptação da data para a versão 1.9, os metadados são lidos utilizando o Xylose e colocados no XML, obedecendo a ordem colocada em https://github.com/scieloorg/document-store-migracao/issues/250#issuecomment-585674304.
Também foram feitas melhorias em testes unitários e correções necessárias.
Rodando os testes unitários: `python setup.py test`, em especial:
- `tests.test_export`
- `tests.test_sps_package`
- `tests.test_conversion`
- `tests.test_processing`
OU
Utilizando o …
=> Completa datas de publicação dos documentos provenientes de HTML

documentstore_migracao/utils/convert_html_body.py, tests/test_convert_html_body.py
Este PR altera a conversão do body HTML para, caso não seja possível obter o body de ativos digitais HTML, definir atributo na tag `a` como "não encontrado" e preservar o link original para possíveis correções manuais.
Em `tests/test_convert_html_body.py` para entender o que é esperado através do teste.
- Converta um artigo originalmente em HTML que contenha algum ativo digital em HTML e que esteja quebrado. Ex: `S1414-32832007000100005`
- Observe que o XML resultado da conversão preserva o link do ativo digital HTML não encontrado.
- Execute o mesmo teste com artigos que contenham ativos digitais em HTML que estejam corretos e a conversão deve permanecer como anteriormente.
Esta é parte da correção do tícket #205
N/A
#210
Nenhuma.
=> Altera import de asset HTML para preservar links quebrados na conversão

documentstore_migracao/exceptions.py, documentstore_migracao/main/__init__.py, documentstore_migracao/main/migrate_logos.py, documentstore_migracao/website/migrate_to_website.py, requirements.txt, setup.py, tests/test_main.py, tests/test_migrate_logos.py, tests/test_migrate_to_website.py
Este PR adiciona a capacidade de migrar os logos do site atual para o site novo, evitando que eles sejam cadastrados manualmente.
Ao rodar o comando de migração, são lidos os periódicos cadastrados no MongoDB do site novo e, para cada um deles, é obtido o logo do site atual, salva-o no diretório de mídias do site, cadastra na tabela image do banco SQLite e atualiza a URL da imagem do logo do periódico no MongoDB.
Caso não exista periódicos no site, um erro é exibido.
Tendo uma instância do OPAC em funcionamento:
- Instale a nova versão com o `setup.py`
- Execute o comando `migrate_logos`. Para informações de utilização, use `-h`
- Caso não exista periódicos no site, observe que um erro é exibido ao executar o comando
- Com os periódicos …
=> Adiciona migração direta para o site dos logos

documentstore_migracao/processing/conversion.py
Ajusta a obtenção da data de publicação do artigo e fascículo na fase de conversão.
Olhando o módulo: 
- documentstore_migracao/processing/conversion.py:18
Com uma instânca `document_store_migracao` rodar a extração para os seguintes: 
[pids.txt](https://github.com/scieloorg/document-store-migracao/files/4288490/pids.txt)
`ds_migracao extract pids.txt`
Rodar a conversão 
`ds_migracao convert`
É importante ter em mente que essa função obtém as datas para artigo e para fascículos. 
Veja a documentação sobre essas datas: https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-pub-date.html
Resultado final do XML quando o fascículo contém somente o ano: 
#263
https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-pub-da …
=> Ajusta a obtenção da data de publicação do artigo e fascículo na fase de conversão.

documentstore_migracao/utils/convert_html_body.py, tests/test_convert_html_body.py
Remove `a[@name]` se é âncora do topo do documento
por commits
`ds_migracao convert --file xml/source/S0102-67202007000100001.xml`
Outros arquivos similares
[source.zip](https://github.com/scieloorg/document-store-migracao/files/4288601/source.zip)
n/a
**antes:**
`fn` não deveria existir
`xref` não deveria existir
**depois:**
Não gerou o `<fn>`
Removido o `xref`
#259
n/a
=> Remove `a[@name]` se é âncora do topo do documento

docs/README.md, docs/quality-assurance.md, documentstore_migracao/main/migrate_articlemeta.py, documentstore_migracao/utils/quality_checker.py, tests/test_migrate_articlemeta.py
Este pull request adiciona um comando que ajuda a verificação de artigos não importados em uma instância.
- `documentstore_migracao/main/migrate_articlemeta.py`
- Obter uma lista de pids migrados ou não para uma instância (dsteste);
- Executar o comando `ds_migracao quality arquivo-de-pids.txt "http://dsteste.scielo.br/article/\$id"`;
- Observar quais artigos não estão disponíveis na instância indicada.
É com muita vergonha que vos digo: não criei testes para este pull request. Não consegui encontrar um modo fácil de criar testes para este PR visto que a funcionalidade em si é dada apenas por realizar requisições HTTP, então seria necessário gerar mocks e mais mocks, perdão.
PS2: Por favor verificar a documentação que foi adicionada.
N/A …
=> Adiciona comando para checar a dispnibilidade de Artigos após a migração

documentstore_migracao/export/sps_package.py, documentstore_migracao/processing/inserting.py, tests/test_inserting.py, tests/test_sps_package.py
Este PR resolve a origem do problema da criação do arquivo JSON gerado pelo comando `ds_migracao import`.
Basicamente, altera os retornos das propriedades `number` e `supplement` do `SPS_Package`, que tentam retornar o dado mais próximo possível do que está representado no XML, tendo em vista que as duas são extraídas da mesma tag: `article_meta/issue`.
Também altera leitura de JSON de saída do comando `import` do `ds_migracao` durante a execução do comando `ds_migracao link_documents_issues` para obter os dados corretamente.
- Empacote artigos órfãos apontados no issue #274 (alguns exemplos no anexo [1])
- Execute o comando `ds_migracao import`
- Verifique o JSON de saída do comando anterior. O número e o suplemento devem estar …
=> Corrige relacionamento entre documentos e fascículo

documentstore_migracao/utils/convert_html_body.py, documentstore_migracao/utils/convert_html_body.txt, documentstore_migracao/utils/convert_html_body_inferer.py, tests/test_convert_html_body.py
Remove o menu de seções do body e as apresenta no menu da esquerda.
Com a correção:
Por commits
Executar a conversão em 
[S0100-879X1997000600002.xml.zip](https://github.com/scieloorg/document-store-migracao/files/4371686/S0100-879X1997000600002.xml.zip)
`ds_migracao convert --file xml/source/S0100-879X1997000600002.xml`
`htmlgenerator xml/conversion/S0100-879X1997000600002.en.xml --nochecks`
Veja a comparação do resultado do master e do tk273
[tk273.zip](https://github.com/scieloorg/document-store-migracao/files/4371679/tk273.zip)
n/a
n/a
#273 
https://jats.nlm.nih.gov/publishing/tag-library/1.3d1/attribute/sec-type.html
=> Corrige os XML que contém "menu" das seções no body

documentstore_migracao/utils/build_ps_package.py, requirements.txt, setup.py, tests/test_build_ps_package.py
Este PR adiciona o otimizador de documentos e ativos digitais no packtools, utilizando o `packtools.XMLWebOptimiser`.
Com CSV contendo documentos XML referenciando ativos digitais TIFF:
2. Verifique o diretório informado na opção `-Ofolder`
3. Observe que o pacote foi gerado com sucesso
Exemplo de CSV: [base_artigos.txt](https://github.com/scieloorg/document-store-migracao/files/4471829/base_artigos.txt)
Este PR não resolve o problema dos arquivos referenciados não encontrados. O ticket #304 foi aberto para resolver este problema.
n/a
Resolve parcialmente o #283 
.
=> Adiciona otimizador de documentos do Packtools

documentstore_migracao/processing/conversion.py, documentstore_migracao/utils/convert_html_body.py, tests/test_convert_html_body.py
O tipo de erro era o mesmo objeto (None) acessando um atributo. Mas acontecia em 3 pontos diferentes, por motivos diferentes.
1) Conversão de notas de rodapé. Tive que revisar/refatorar os pipes relacionados pois no ponto onde ocorre o erro, o resultado do XML esperado naquele ponto era diferente do obtido.
2) Conversão de tabelas (ativos digitais). Resolvido conforme sugerido
3) Ausência de body. Um dos pipes estava removendo o body por estar vazio. Passou a manter o elemento body, vazio.
Então, foram 3 soluções diferentes. Uma delas foi a sugestão do comentário
https://github.com/scieloorg/document-store-migracao/issues/293#issuecomment-611654852
Por commits
Estabeleça os passos necessários para que a funcionalidade seja testada manualmente pelo revisor.
```python
python setup.py test …
```
=> Corrige erros na conversão ao tentar acessar métodos em objeto vazio

documentstore_migracao/utils/convert_html_body.py
Este PR corrige pipe `AssetThumbnailInLinkAndAnchorAndCaption()` na conversão do body HTML. Simplesmente altera checagem de nó por conta do retorno, que é uma lista. Caso `findall` não encontre nenhum elemento, retorna uma lista vazia ao invés de None, como era esperado. O if segunte que confere a tag `a` só faz sentido após a mudança de `p_next`, ou seja, dentro do if anterior.
Em `documentstore_migracao/utils/convert_html_body.py`, L1880
1. Extrair os seguintes documentos:
- S0074-02762002000900021
- S0100-84042009000200014
- S0103-64402007000100012
2. Converter os documentos com o comando `ds_migracao convert`
3. Observe que os XMLs foram convertidos 
Este PR resolve pontualmente este problema e leva em consideração os pontos das premissas de migração, não focando em resolver problemas …
=> Corrige pipe AssetThumbnailInLinkAndAnchorAndCaption

documentstore_migracao/processing/conversion.py, documentstore_migracao/utils/convert_html_body.py, tests/test_convert_html_body.py
Corrige a issue "Referências dentro de uma lista HTML não são retiradas do body e erro ocorre" (#291)"
Na verdade, são dois problemas diferentes. Mas foram tratados neste PR.
Ao investigar o problema, foi identificado que um dos pipes relacionados com as seções (`<sec/>`) estava inserindo `<sec/>` "acima" do "body", modificando o "primeiro nó da árvore" que seria esperado ser o "body", causando uma exceção antes de gravar o XML em arquivo.
Os pipes relacionados às seções tiveram que ser refatorados.
Por casualidade, o erro sobre as referências não removidas, está sendo registrado no migracao.log, fazendo parecer que era a causa do problema. 
Por estar no título da issue, foi tratado juntamente, mesmo que sem nenhuma relação.
Por commits
```shell
ds_migracao --loglevel DEBUG convert --file …
```
=> Corrige a issue "Referências dentro de uma lista HTML não são retiradas do body e erro ocorre" (#291)"

documentstore_migracao/export/sps_package.py, documentstore_migracao/utils/build_ps_package.py, tests/test_build_ps_package.py
Adiciona busca à alternativas aos ativos digitais referenciados nos XMLs nativos. Essa busca é feita somente se os ativos digitais não forem encontrados como referenciados no XMLs: sem extensão de arquivo, com extensões diferentes. Caso a busca encontre alternativas, o XML coletado é atualizado com as alternativas.
Com CSV contendo documentos XML referenciando ativos digitais não encontrados:
2. Verifique o diretório informado na opção `-Ofolder`
3. Observe que o pacote foi gerado com sucesso
Exemplo de CSV: [base_artigos.txt](https://github.com/scieloorg/document-store-migracao/files/4471829/base_artigos.txt)
Existem alguns problemas que não são resolvidos neste PR, como ausência …
=> Altera coleta de ativos digitais referenciados nos XMLs nativos

documentstore_migracao/utils/build_ps_package.py, tests/test_build_ps_package.py
Este PR paraleliza o empacotamento dos XMLs nativos, seus ativos digitais e suas manifestações PDF. Também foram alterados métodos do processo para melhorar os logs, tanto nas mensagens logadas como nas informações nelas contidas.
Com CSV contendo documentos XML referenciando ativos digitais não encontrados:
2. Verifique o diretório informado na opção `-Ofolder`
3. Observe que o pacote foi gerado com sucesso
4. Observe que agora a aplicação executa o empacotamento em paralelo e a barra de progresso é exibida
Exemplo de CSV: 
[base_artigos_erro.txt](https://github.com/scieloorg/document-store-migracao/files/4495184/base_artigos_erro.txt)
.
.
#310 
.
=> Paraleliza o empacotamento dos XMLs nativos

documentstore_migracao/utils/convert_html_body.py, tests/test_convert_html_body.py
Este PR trata tags `a` inválidas que tem atributo `src` ao invés de `href` para o link. Também verifica a inexistência do atributo `href` em tags `a` antes de tratá-la pela conversão, pois é um atributo obrigatório.
1. Extraia os documentos em [pids_issue_299.txt](https://github.com/scieloorg/document-store-migracao/files/4470707/pids_issue_299.txt) através do comando `ds_migracao extract`
2. Converta os documentos com o comando `ds_migracao convert`
3. Todos os documentos devem ser convertidos com sucesso
Conforme reportado no https://github.com/scieloorg/document-store-migracao/issues/299#issuecomment-617922715, mesmo sem este PR foi possível converter quase todos os documentos. O único documentos que tem efeito em sua conversão é o …
=> Corrige tag a inválida e prevê existência de tags inválidas

documentstore_migracao/utils/build_ps_package.py, tests/test_build_ps_package.py
Para padronizar o caminho relativo onde o XML nativo deveria estar para a estrutura do site atual, lê as informações necessárias do CSV e remonta o path com o acrônimo do periódico, label do fascículo e nome do arquivo XML do campo `file` do CSV.
Em `tests/test_build_ps_package.py`, para entender os paths como são esperados hoje.
Com CSV atualizado, contendo as informações do acrônimo do periódico e label do fascículo, :
2. Verifique o caminho que os documentos XMLs estão sendo buscados, que deve ser `<acrônimo>/<label do fascículo>/<arquivo XML>`
3. Observe que os diretórios no caminho informado no argumento `-Ofolder` do comando segue o padrão esperado do empacotamento
[Arquivo com paths de documentos fora do padrão esperado …
=> Padroniza caminho do documento XML nativo

documentstore_migracao/utils/build_ps_package.py, tests/test_build_ps_package.py
Com novo formato de CSV, também foi necessário alterar o método de atualização de XMLs nativos para que duas novas colunas são esperadas em cada linha do arquivo.
Em `documentstore_migracao/utils/build_ps_package.py`
Com o CSV novo, contendo as colunas de acrônimo e label do fascículo, execute o comando `ds_migracao pack_from_site`. Nenhum erro deve ocorrer.
Complementa o PR #321.
n/a
#318
.
=> Ajusta método de atualização de XML nativo para receber novo CSV

documentstore_migracao/export/sps_package.py
Este pull request resolve principalmente o erro de serialização durante a atualização de documentos nativamente XML. Também corrige acesso a objetos vazios durante atualização da data de publicação.
- `documentstore_migracao/export/sps_package.py` L: `80`
- Fazer o download da lista de documentos com erro em [1];
- Realizar o empacotamento com a lista [1];
- Verificar que os documentos não apresentam mais erro de _enconding_.
O erro relacionado com o documento `S0036-46652014000300185` não foi tratado
porque é um problema de XML e precisa ser corrigido manualmente. Segue o erro:
```
Exception: Entity 'squf' not defined, line 546, column 99 (0036-4665-rimtsp-56-03-185.xml, line 546)
```
N/A
closes #325 
[[1] - …
=> Corrige erros de serialização durante a atualização de artigos XML

documentstore_migracao/export/sps_package.py, documentstore_migracao/utils/build_ps_package.py, tests/test_build_ps_package.py, tests/test_sps_package.py
Este PR tenta resolver problema da falta do idioma original do documento em XML nativo através de dado presente na base ISIS, lido do CSV que é usado para o empacotamento. Este dado somente será inserido no XML caso não esteja no documento.
Em `documentstore_migracao/utils/build_ps_package.py`, L139-L144.
Com CSV contendo documentos em XML nativo:
- Execute o comando para o empacotamento `ds_migracao pack_from_site`
- Para documentos XML que não possuíam o idioma original na tag `article`, este agora deve estar presente
- Verifique se todos os pacotes foram criados com seus respectivos `manifest.json`
[1] - [CSV com documentos sem idioma](https://github.com/scieloorg/document-store-migracao/files/4691754/nativos-issue-329.txt)
Este problema foi detectado durante o `import` ao Kernel mas, …
=> Adiciona idioma original ao XMLs nativos quando não houver

documentstore_migracao/export/sps_package.py, documentstore_migracao/utils/build_ps_package.py, documentstore_migracao/utils/manifest.py, documentstore_migracao/utils/xylose_converter.py, tests/test_build_ps_package.py, tests/test_xylose_converter.py
Este pull request corrige a atualização de datas durante o empacotamento de XMLs nativos. Também melhora a função que faz o _parser_ de strings para datas e também corrige um bug na atualização do elemento `pub-date` do xml evitando duplicidades.
- `documentstore_migracao/export/sps_package.py`
- Baixar a lista de documentos a serem empacotados [1];
- Realizar o empacotamento da lista [1];
- Realizar o _"import"_ dos documentos no kernel;
- Verificar que os documentos com datas válidas foram importados;
O comportamento de decisão sobre quando atualizar ou não as datas deve ser questionado.
N/A
#328
[[1] - issue-328-documentos.txt](https://github.com/scieloorg/document-store-migracao/files/4698046/issue-328-documentos.txt)
N/A
=> Corrige bug na atualização de datas durante o empacotamento de XMLs nativos

requirements.txt
Este PR atualiza o Packtools para a versão que trata exceção `DecompressionBombError`. O Pillow trata abertura de arquivos de imagem que passam do limite de resolução pré estabelecido como um "potencial ataque DOS". Esta
versão do Packtools trata a exceção lançada e emite uma exceção apropriadamente, permitindo que esta aplicação já trate-a adequadamente.
O impacto final na aplicação é que o erro seja informado de forma adequada e que a otimização do pacote SPS não seja interrompida.
Em `requirements.txt`
Com CSV em anexo [1]:
- Execute comando `ds_migracao pack_from_site` para empacotamento de XMLs Nativos
- Verifique os pacotes criados e, com exceção das imagens com a resolução maior, os pacotes devem conter as imagens que os compõem.
- O empacotamento deve finalizar sem problemas.
Este …
=> Atualiza versão do Packtools que trata exceção do Pillow

requirements.txt
Atualiza a versão do JPype para a versão 1.0.1
No arquivo de requirements.txt
Em ambiente python 3.8.X, realize a instalação do document-store-migracao e execute alguns dos comandos para migração as base de dados title ou issue.
Por exemplo: 
```
migrate_isis extract issue.mst --output ./issue.json 
```
Repare que não é levantado qualquer exceção! 
Durante minha re-instalação do projeto localmente me deparei com o seguinte erro:
=> Atualiza a versão do JPype para 1.0.1 permitindo o uso de versões do python > 3.8.X

documentstore_migracao/config.py, documentstore_migracao/main/migrate_articlemeta.py, documentstore_migracao/processing/conversion.py, documentstore_migracao/processing/inserting.py, documentstore_migracao/tools/constructor.py, documentstore_migracao/utils/pid_manager.py, tests/test_migrate_articlemeta.py, tests/test_tools.py
Esse PR tem como objetivo adicionar a capacidade de verificar a existência do PID v3 na base de dados do PIDs do XC através do PID v2.
**IMPORTANTE**: Não é necessário que o tíquete https://github.com/scieloorg/prodtools/issues/5 tenha sido realizado para aprovação desse PR. 
Verifique os commit tive um cuidado em deixar os commits legíveis e cronologicamente de acordo com a evolução do desenvolvimento da tarefa, portanto é um bom começo !!! :-)
Bom para testar esse commit é necessário ter o grande parte do ambiente do SPF montado. Para isso é possível acessa um documento que tem como objetivo apoiar na tarefa de ter esse ambiente: https://docs.google.com/document/d/1W__CZoIXuOiFMYQGciBRtpM39Y0aMEBKupBWzCYxyRo/edit#
Se tudo der certo e logo o nosso parceiro @rafaelpezzuto nós presenteará …
=> [FASE 4] Tk335 - Adiciona capacidade de verificar o PID na versão 3 no banco de dados de PIDs do XC.

Dockerfile, requirements.txt, setup.py
Este PR possibilita a conexão da aplicação com bancos de dados PostgreSQL. Adiciona `psycopg2-binary` como dependência da aplicação e `postgresql-dev` no Dockerfile para possibilitar a construção da imagem com a dependência.
Commit 9aa1cdf
- Extraia o anexo [1] na raíz do projeto
- Com uma instância de PostgreSQL e uma base de dados
- Execute o comando:
```
ds_migracao --loglevel DEBUG import --uri mongodb://0.0.0.0:27017/ --db document-store \
--minio_host 0.0.0.0:9000 --minio_access_key minio --minio_secret_key senha --folder xml/site_sps_packages_tk_349 --output json/nativos-issue-349.json --pid_database_dsn <DSN do PostgreSQL>
```
- Verifique se foi criado um registro com o PID V2 e V3 na tabela `pid_versions`
.
.
- [1] - [Diretório teste do site - …
=> Instala o psycopg2 para possibilitar conexão com PostgreSQL

documentstore_migracao/utils/build_ps_package.py, tests/test_build_ps_package.py
Este pull request corrige a primeira parte do problema relacionado com a identificação das manifestações dos XMLs nativos. A partir deste ponto, a cópia dos `pdfs` passará pela seguinte precedência
1) Nome do pdf com prefixo;
2) Nome do pdf  com sufixo;
Os artigos que não possuírem tradução não serão afetados.
- `documentstore_migracao/utils/build_ps_package.py` L `243`
- Execute o empacotamento para o seguinte documento:
```csv
S0103-05822021000100401,,rpp/v39/1984-0462-rpp-39-e2019097.xml,20210000,20200618,20200618,RPP,v39,en
```
- Verifique os pdfs;
- Verifique o arquivo de manifest;
- Observe que os nomes dos pdfs copiados e de dentro do arquivo `manifest` estão compatíveis;
N/A
N/A
#354
N/A
=> [FASE 4] Corrige a formação do nome do PDF durante o empacotamento para XML nativos

documentstore_migracao/exceptions.py, documentstore_migracao/main/migrate_articlemeta.py, documentstore_migracao/processing/rollback.py, tests/test_rollback.py
Este PR adiciona comando para reverter operação de rollback nos documentos importados para o Kernel, além das relações com os bundles e os registros de mudança.
Este comando executa o rollback baseado no documento resultante do comando `ds_migracao import`.
É recomendado que a revisão seja feita por commit. Inicie por 939f53c.
- Execute o comando `mongoexport` na base do Kernel de produção para obter os dados do banco e `mongoimport` para um MongoDB de teste OU execute o comando `ds_migracao import` de alguns pacotes de documentos
- Obtenha o arquivo JSON produzido pela importação dos documentos para o Kernel
- Execute o comando `ds_migracao rollback --help`
- Verifique as instruções do comando
- Execute o comando conforme instruções do help, informando os dados para a conexão com o …
=> [FASE 4] Adiciona comando para desfazer import para o Kernel

documentstore_migracao/processing/inserting.py, tests/test_inserting.py
Este pull request corrige "super" detecção de manifestações que ocorria durante a fase de importação para documentos com arquivos suplementares.
- `documentstore_migracao/processing/inserting.py` L: `238`
- Realize o empacotamento do documento utilizando o CSV [1];
- Realize a importação do documento recém empacotado;
- Acesse o documento no kernel;
- Verifique o arquivo 0102-3306-abb-0102-33062019abb0286-s.pdf foi incluído como PDF;
- Verifique que o arquivo 0102-3306-abb-0102-33062019abb0286-s.pdf é na verdade um asset;
Indique um contexto onde as modificações se fazem necessárias ou passe informações que contextualizam
o revisor a fim de facilitar o entendimento da funcionalidade.
N/A
[[1] - documentos-com-suplementos.txt](https://github.com/scieloorg/document-store-migracao/files/52933 …
=> Corrige a detecção de manifestação durante o import de documentos

scripts/loggeranalyzer.py, setup.py, tests/scripts/test_loggeranalyzer.py
Esse PR adiciona novas expressões regulares para o script loggeranalyzer.py, com o objetivo de estruturarmos o log do processamento da fase de pack e importação, para realizarmos consultas com **jq**.
Olhando a história dos commits e olhando o script `loggeranalyzer.py`
- Baixe o arquivo de log: 
[migracao.log.zip](https://github.com/scieloorg/document-store-migracao/files/5201469/migracao.log.zip)
- Execute `python scripts/loggeranalyzer.py path-para-arquivo-de-log -s import`;
- Visualize as saídas em formato JSON indicando:
- Arquivo de Manifest não encontrado
- Arquivo XML não encontrado
- Erro de analise no XML
- Bundle não encontrado 
- Fascículo não encontrado
- Erro de importação de pacote
Esse script esta atualmente analisando os logs da fase de empacotamento do site e os logs da …
=> Adiciona a analise do arquivo do log para o passo da importação (import). 

documentstore_migracao/export/sps_package.py, tests/test_sps_package.py
Esse **PR** corrigi um erro encontrado no momento de migração do seguinte XML: https://kernel.scielo.br/documents/hQXRCQk4CzrbtVs3FRvkGcB
Reparem que existe no nó ``article-meta`` items  repetidos: **volume**, **fpage**, **lpage**, **issue**....
O processamento estava obtendo o último “item”.
No módulo: documentstore_migracao/export/sps_package.py:217
Sugiro rodar os testes unitários.
N/A
N/A
Esse PR é referente ao bug: https://github.com/scieloorg/document-store-migracao/issues/363
N/A
=> Garante que os atributos retornado na propriedade ``parse_article_meta`` sejam sempre os item abaixo da nó ``article_meta``

documentstore_migracao/export/sps_package.py, documentstore_migracao/main/migrate_articlemeta.py, documentstore_migracao/processing/inserting.py, documentstore_migracao/processing/packing.py, documentstore_migracao/utils/build_ps_package.py, tests/test_build_ps_package.py, tests/test_sps_package.py
Corrige o valor do "order" no XML
por commits
Crie um XML que contenha:
- pid v2 com formato válido, ou seja, 23 digitos, sendo os últimos 5, numéricos.
- fpage com valor alfanumérico
- ausência de `<article-id pub-id-type="other"/>`
Exemplo real: S0104-14282017000100000
Execute os procedimentos da migração: pack e import, então verifique que no XML e no JSON criou "order": "00000", no lugar de "000E1".
n/a
n/a
#365 
n/a
=> Corrige o valor do "order" no XML

documentstore_migracao/utils/xml.py, tests/test_pipeline.py
Este pull request corrige um problema percebido durante a atualização dos artigos em HTML. Algumas citações possuem caracteres como `&gt;`, estes não devem ser convertidos ('escapados') para a sua representação (`>`) afim de evitar a má formação do XML convertido.
- `documentstore_migracao/utils/xml.py` L:  `22`
- Extraia e baixe os referenciados em [1];
- Busque pelos respectivos arquivos JSON de cada documento em `/mnt/vol_dsteste/migracao/html_migracao/paragraphs` no servidor `DSTESTE`;
- Atualize as citações por meio do comando `mixed-citations update`;
- Tente converte os arquivos recém atualizados;
- Os passos acima podem ser executados sem este PR para reproduzir os problemas.
Esta função de _escape_ foi introduzida em algum outro …
=> Corrige erro durante atualização das <mixed-citations> de artigos HTML

documentstore_migracao/export/sps_package.py, documentstore_migracao/processing/packing.py, tests/test_build_ps_package.py, tests/test_sps_package.py
Atualiza os XML provenientes do HTML com a tag `<article-id pub-id-type="other"/>` usando os 5 últimos dígitos de PID v2.
Nota: para os XML nativos, a tag é opcional porque na sua ausência vale o valor de `fpage`, mas nos HTML, o valor de `order` era sempre fornecido na marcação e não era assumido o valor de `fpage`, por este motivo, para manter a consistência, o ideal é sempre completar o XML (do html) com `<article-id pub-id-type="other"/>`.
por commits
Veja o issue #320 
n/a
n/a
#320 
n/a
=> [dsm][html] Atualiza os XML com a tag `<article-id pub-id-type="other"/>` usando os 5 últimos dígitos de PID v2

documentstore_migracao/export/sps_package.py, tests/samples/S0044-59672003000300002_sps_completo.xml, tests/samples/S0044-59672003000300002_sps_incompleto.xml, tests/test_sps_package.py
Obtém os dados de rendition do próprio XML no lugar de consultar o AM
por commits
Executando o `pack` (do html)
n/a
n/a
#385 
n/a
=> Obtém os dados de rendition do próprio XML no lugar de consultar o AM

documentstore_migracao/utils/build_ps_package.py, tests/test_build_ps_package.py
Este PR altera o empacotador de XMLs nativos para verificar se o caminho registrado no CSV extraído da base ISIS existe no diretório fonte de XMLs, informado no parâmetro `-Xfolder`. Se este caminho existir, utiliza-o para o empacotamento. Caso contrário, utiliza os dados do CSV para montar o caminho relativo do XML.
Commit c1e8b3f.
1. Execute o comando de empacotamento de XMLs nativos para /mnt/vol_dsteste/migracao/2014_native_xml.csv.
2. Os arquivos com erro apontados no issue #368 devem ser localizados e empacotados.
3. Os erros registrados anteriormente no log, apontados no issue #368, não devem ser mais registrados.
.
N/A
Closes #368.
.
=> Altera BuildPSPackage.get_existing_xml_path p/ verificar file_path

documentstore_migracao/export/sps_package.py, documentstore_migracao/processing/packing.py, tests/samples/S0044-59672003000300002.json, tests/test_processing_packing.py, tests/test_sps_package.py
Corrige o caminho do pdf considerando que é montado a partir de dados registrados no "issue", ou seja, considerando os valores preenchidos no campo número. Se está em maiúsculas, manter maiúsculas.
por commits
Executando o pack para o `S0004-282X2002000200003` e verificando que com a correção o seu pdf foi encontrado.
n/a
n/a
#392
n/a
=> [html][pack] Corrige o caminho do pdf considerando que é montado a partir de dados registrados no "issue"

documentstore_migracao/processing/packing.py, tests/test_processing_packing.py
Flexibiliza a estratégia para encontrar o arquivo do ativo digital, identificando nomes de arquivos similares, desconsiderando letras maiúsculas/minúsculas.
por commits
Executar `ds_migracao pack` para arquivos do ano de 2010 e 2009. Veja mais detalhes em #396
Este PR não trata o problema:
- Procura por 07t3.gif mas existe 07t03.gif
n/a
#396
https://docs.python.org/3/library/difflib.html#difflib.get_close_matches
=> [html][pack] Flexibiliza a estratégia para encontrar o arquivo do ativo digital

documentstore_migracao/processing/packing.py, tests/test_processing_packing.py
Caso o ativo digital é `seta.gif`, procura em `htdocs/img`
por commits
Tenha:
- um XML que contenha `<graphic xlink:href="/img/revistas/acron/vol/seta.gif"/>` no caminho definido por `VALID_XML_PATH`
- no caminho `SOURCE_IMG_FILE/img/revistas/acron/vol` não deve existir seta.gif
- no caminho `SOURCE_IMG_FILE/img/` deve existir seta.gif
Execute:
`ds_migracao pack --file <VALID_XML_PATH>/documento.xml`
Note que em `SPS_PKG_PATH=SAMPLES_PATH` (ou `INCOMPLETE_SPS_PKG_PATH`) é gerado o pacote correspondente e um arquivo correspondente a seta.gif é gerado.
n/a
n/a
#400
n/a
=> [html][pack] Caso o ativo digital é `seta.gif`, procura em `htdocs/img`

docs/usage.md, documentstore_migracao/processing/compare_articles_sites.py
Na criação desse PR não havia sido enviado a documentação sobre esse comando e existia um bug na comparação entre a nota de corte e o valor retornado da função que avalia a similaridade.
Olhando os commits suspeito que seja suficiente.
Para realizar o teste é necessário ter um **PID** que faça a comparação e que esse número seja próximo de um interiro, exemplo 70,1 ou 43,00009, portanto, coloco aqui um **PIDs** em que o valor da similaridade é próximo de 90. 
**S0044-59672015000200239**
Crie um arquivo com o pid: **S0044-59672015000200239**, chamado pids.txt
E execute o seguinte comando: 
```shell
ds_migracao check_similarity --similarity_input pids.txt --similarity_output sim.jsonl --cut_off_mark 90
```
Verifique que no arquivo **sim.jsonl** não consta o texto da comparação, pois o texto …
=> Adiciona a documentação do comando de similaridade e corrige a comparação entre o valor da similaridade e a "nota de corte".

documentstore_migracao/config.py, documentstore_migracao/processing/compare_articles_sites.py, requirements.txt
Esse PR é resultado de diversas execuções desse código, onde identificamos as partes do texto que é necessário remover/avaliar para que a similaridade seja mais assertiva.
Outro ponto que está contemplado nesse PR é a capacidade de retentar a obtenção dos textos dos artigos nos dois site (novo e clássico)
Através dos commits.
Executando o código e verificando a taxa de similaridade. 
Para testar as re-tentativas é possível executando o código com o seguinte comando: 
```shell
ds_migracao check_similarity --similarity_input pids_html.txt --similarity_output similarity_html.jsonl
```
e após um tempo desativando a interface de rede local para verificar que a execução não é interrompida.
=> Adiciona re-tentativas na função fetch_articles e adiciona os ajustes de configuração.

scripts/make_reports.py
Script que lê o resultado de `html_migracao/<anos>/logs` e `html_migracao/<anos>/linked2kernel`
por commits
`python .dsm/scripts/make_reports.py 2009 2014 html_migracao/_reports_
`
n/a
n/a
n/a
n/a
=> Melhoria do script scripts/sumarize_reports.py

docs/usage.md, documentstore_migracao/export/sps_package.py, documentstore_migracao/main/migrate_articlemeta.py, documentstore_migracao/processing/packing.py, documentstore_migracao/utils/build_ps_package.py, tests/test_build_ps_package.py, tests/test_sps_package.py
Completa documentos XML que não tem nenhum `<issn/>` dentro de `journal-meta`. Com isso, o documento não terá problema na execução do comando `link_documents_issues`
por commits
Execute o `pack` ou `pack_from_site` em XML que não possuem `<issn/>` em `<journal-meta/>`.
Como resultado, será criado `<issn/>` a partir dos dados encontrados em um arquivo json que é passado como parâmetro dos comandos `pack` ou `pack_from_site` (`--issns-jsonfile`)
O formato deste arquivo é:
```json
{
"1234-0987": {"epub":  "1234-0987", "ppub": "3456-0987"},
"3456-0987": {"epub":  "1234-0987", "ppub": "3456-0987"},
"1264-5900": {"epub":  "1264-5900", "ppub": "6456-5900"},
"6456-5900": {"epub":  "1264-5900", "ppub": "6456-5900"}
}
```
```console
export SOURCE_IMG_FILE=/mnt/vol_dsteste/migracao/htdocs
export …
```
=> Completa documentos XML que não tem nenhum `<issn/>` dentro de `journal-meta`

documentstore_migracao/utils/convert_html_body.py, documentstore_migracao/utils/xml.py, tests/test_utils.py
Troca o `w:` que é um prefixo de namespace para `w-` antes da conversão
por commits
Crie o arquivo tk375.txt contendo:
```
S0001-37652010000400028
S0004-282X1981000400015
```
Deixe os diretório `xml/source` e `xml/conversion` vazios
Execute os seguintes comandos:
```console
ds_migracao --loglevel DEBUG extract tk375.txt
ds_migracao --loglevel DEBUG convert 
```
Verifique que a conversão termina sem levantamento de exceções e que os XML em `xml/conversion` estão bem formados.
Uma alteração similar foi feita para mixed-citations (https://github.com/scieloorg/document-store-migracao/pull/382)
Com esta alteração, entraram 30 documentos hoje no new.scielo.br (https://docs.google.com/document/d/1DrRPArvm8pzpuwRzbZQV3H7q3YoQ9dPH10BhfK89Uko/edit#heading=h.mhp2kzv8lg1l)
n/a
Ver issue #375, …
=> [convert] Troca o `w:` que é um prefixo de namespace para `w-` antes da conversão

documentstore_migracao/utils/convert_html_body.py
Este PR corrige problema na junção de url na propriedade FileLocation.remote, usada na conversão do body HTML. O `urllib.parse.urljoin()` é utlizado, pois trata de forma mais adequada para casos de junção de URL. Assim, a exceção não ocorreria, já que o primeiro atributo informado é uma URL válida.
Commit 0736fc3.
1. Execute a conversão do XML do documento PID v2 `S0104-42302013000600016`.
2. O arquivo deve ser convertido sem interromper a execução.
3. A tag deve aparecer preservada no XML convertido, pois o link está originalmente incorreto.
.
.
#420.
.
=> [conversão] Corrige propriedade FileLocation.remote p/ fazer a combinação da URL

documentstore_migracao/utils/convert_html_body.py
Este PR altera importação de HTMLs referenciados em artigos HTML para não interromper conversão quando o link para o arquivo HTML tem mais de uma âncora no link.
O método `Remote2LocalConversion._imported_html_file()` precisa somente do caminho do arquivo HTML e âncoras não são usadas nesta parte do código.
Observe que o método `Remote2LocalConversion._imported_html_file()` não utliza a variável `anchor` a ser obtida no no resultado do `str.split()`.
1. Execute o comando
```ds_migracao convert --file=<caminho para XML extraído>```
OU
```./ferramentas/migracao.sh <diretorio ano> <caminho para arquivo com os PIDs v2> <diretório raíz destino da execução>```
Os PIDs reportados no issue devem estar contidos no arquivo de PIDs.
.
.
#421 
.
=> [conversão] Altera importação de HTMLs referenciados em artigos HTML para não interromper conversão com mais de uma âncora no link

documentstore_migracao/utils/convert_html_body.py
Este PR tenta previnir exceção de complemento de âncoras com texto completo do label com numéricos não decimais.
Commit 6e25a41.
1. Execute o comando
```ds_migracao convert --file=<caminho para XML extraído>```
OU
```./ferramentas/migracao.sh <diretorio ano> <caminho para arquivo com os PIDs v2> <diretório raíz destino da execução>```
Os PIDs reportados no issue devem estar contidos no arquivo de PIDs.
.
.
#422.
.
=> [conversão] Altera conversão de âncora para prever dígitos não decimais

documentstore_migracao/processing/packing.py
Registra os erros ocorridos na fase de empacotamento de xml sintetizados. Corrige o bug de ter deixado de registrar os erros.
por commit
Tente empacotar um xml sintetizado
```python
ds_migracao --loglevel DEBUG pack --file documento_mal_formado.xml
```
Note que registra a mensagem de erro
n/a
n/a
Não foi criado issue para fazer esta correção. Identifiquei problema ao processar um lote de xml sintetizados que não estavam presentes no kernel (https://github.com/orgs/scieloorg/projects/4#card-54097599). 
Corrige bug inserido por https://github.com/scieloorg/document-store-migracao/pull/386/commits/0284facf6a8a591473bd5085d58e1f0a94b1db1a
Indique as referências utilizadas para a elaboração do pull request.
=> Registra as exceções levantadas por `pack_article_xml`

documentstore_migracao/utils/convert_html_body.py
Este PR altera a conversão de tags `img` para verificar antes se o atributo `src` está presente e se tem valor. Em caso negativo, não faz a conversão, preservando a tag como entrou.
Commit 09adce4.
1. Execute o comando
```ds_migracao convert --file=<caminho para XML extraído>```
OU
```./ferramentas/migracao.sh <diretorio ano> <caminho para arquivo com os PIDs v2> <diretório raíz destino da execução>```
Os PIDs reportados no issue devem estar contidos no arquivo de PIDs.
2. Verifique se os XMLs foram convertidos sem interromper a aplicação e com as tags com problema preservadas.
Os dois casos reportados no issue estão com erro no HTML extraído:
`S0073-47212010000300010`
- tag no body HTML incorreta: `<img sr="" c="/img/revistas/isz/v100n3/fem.jpg" align="absmiddle" />` …
=> [dsm][convert] Antes de converter tag HTML img, verifica se há atributo src
